### ISSUE TITLE
`min_cardinality` of `Pooling`'s `has_input` in v7.7.0 incompatible with NEON data

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1014]
```yaml
Pooling:
  is_a: PlannedProcess # from core.yaml
  slots:
  slot_usage:
    has_input:
      minimum_cardinality: 2
```

vs

```json
{
    "has_input": [
        "nmdc:bsm-11-smjd5w33"
    ],
    "has_output": [
        "nmdc:procsm-11-9jk6qx12"
    ],
    "id": "nmdc:poolp-11-s2x4de34",
    "name": "ABBY_003-O-20170607-COMP-DNA1"
}
```
