### ISSUE TITLE
`jgi_portal_identifiers` isn't attached to anything; make a `jgi_portal_study_identifiers` and mix in `jgi_portal_identifiers`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1041]
Starting with

```yaml
  jgi_portal_identifiers:
    mixin: true
    description: identifiers for entities according to JGI Portal
```

add

```yaml
  jgi_portal_study_identifiers:
    is_a: study_identifiers
    mixins:
      - jgi_portal_identifiers
```

And associate the new `jgi_portal_study_identifiers` with `Study`
cc @aclum
