### ISSUE TITLE
Provide examples with descriptions for all four leaves of `dois`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1046]
like 

```yaml
  publication_dois:
    is_a: dois
    description: One or more DOIs that links a study, or similar entity, to a publication.
    examples:
      - value: doi:10.1126/science.1058040
        description: publication_dois link to a prose document, preferably a peer-reviewed journal article.
          Should not be used to link to datasets or administrative information like funding requests or awards
```
