### ISSUE TITLE
Add link to slot: elevation to help people complete this field

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1053]
Finding elevation based on lat_lon can be difficult. Google maps doesn't provide elevation easily.

Add this link to the slot guidance for elevation
https://www.advancedconverter.com/map-tools/find-altitude-by-coordinates 

This will help users complete this field more easily.

- [x] Update NMDC schema slot: elevation comments
- [x] Update NMDC submission schema slot: elevation comments so the link will appear in the data harmonizer column help
- [ ] Sync subport with new schema

FYI @turbomam , @brynnz22 , @pkalita-lbl

**Comment by brynnz22** [comment]
Comments have been added to `elev` in the nmdc schema.

**Comment by mslarae13** [comment]
So this just needs merged and the subport updated ? (prod, dev, and sandbox)

@pkalita-lbl

**Comment by pkalita-lbl** [comment]
Yeah at some point I can build a new release of `submission-schema` off of the latest `nmdc-schmea` and the bring that into `nmdc-server`. Once that's done the change will be visible in the submission portal on dev. Propagating to sandbox and prod will happen whenever it happens based on the release schedule.

**Comment by mslarae13** [comment]
We'll have submission portal updates for the UF squad, we can just plan to test / make sure all these changes are pushed when we do that update.

**Comment by turbomam** [comment]
## Review

- `elev` is asserted as a Biosample slot in file `src/schema/nmdc.yaml` form the nmdc-schema.
- One part of `make all` is detecting which `Biosample` and `OmicsProcessing` slots are to be imported from MIxS. SInce these terms are imported, we don't generally make any changes to them other than giving them a more structured `range`. But we can assert that they should be used in a cusotmized way int eh context of some class.

Here is the `slot_usage`for `elev` in class `Biosample` in the nmdc-schema.

```yaml
    slot_usage:
      elev:
        title: elevation, meters
        range: float
        comments:
          - All elevations must be reported in meters. Provide the numerical portion only.
          - Please use https://www.advancedconverter.com/map-tools/find-altitude-by-coordinates, if needed, to help estimate the elevation based on latitude and longitude coordinates.
        examples:
          value: 100

```

tl;dr: the "find-altitude-by-coordinates" comment is present in the nmdc-schema
