### ISSUE TITLE
who/what is responsible for declaring and monitoring `data_portal_subset` elements?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1342]
This is a question about using subsets to let responsible parties know when a change in modeling may effect portal functionality.

The nmdc-schema has a `data_portal_subset`. It is documented on this page: https://microbiomedata.github.io/nmdc-schema/DataPortalSubset/

```yaml
data_portal_subset:
  description:
    Subset consisting of entities that Kitware/nmdc-server use to populate the data portal.
  comments:
    - Schema authors are responsible for alerting and supporting Kitware and nmdc-server authors 
      about changes they will have to make if entities labeled with data_portal_subset are modified.
    - Assignment of the data_portal_subset is incomplete in the schema.
```

**I really like the spirit of this subset, but am concerned that** 
- the way it is being applied to schema elements is inconsistent 
- the communication responsibilities are be easy to forget.

For example, when the DOI modelling was changed from multiple free standing slots to a class, that had an impact of the SubmissionPortal. Should we have a submission_portal_subset? Who communicate the new modeling to SubmissionPortal maintainers?

----

## sub-issues about the subset documentation pages:

- [ ] the documentation page changes the case from `data_portal_subset` to DataPortalSubset
- [ ] the documentation page does not display the `description` or `comments`.
- [ ] the documentation page lists the slots that are in the subset. If classes had been placed into the subset, would they also appear on the page?
