### ISSUE TITLE
what's the significance of saying that a (`Biosample`?) slot `is_a attribute`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1356]
https://microbiomedata.github.io/nmdc-schema/attribute/ only has 16 subproperties, out of the ~ 500 `Biosample` slots.

1. [zinc](https://microbiomedata.github.io/nmdc-schema/zinc/)
2. [manganese](https://microbiomedata.github.io/nmdc-schema/manganese/)
3. [ammonium_nitrogen](https://microbiomedata.github.io/nmdc-schema/ammonium_nitrogen/)
4. [nitrate_nitrogen](https://microbiomedata.github.io/nmdc-schema/nitrate_nitrogen/)
5. [nitrite_nitrogen](https://microbiomedata.github.io/nmdc-schema/nitrite_nitrogen/)
6. [lbc_thirty](https://microbiomedata.github.io/nmdc-schema/lbc_thirty/)
7. [lbceq](https://microbiomedata.github.io/nmdc-schema/lbceq/)
8. [env_package](https://microbiomedata.github.io/nmdc-schema/env_package/)
9. [gold_path_field](https://microbiomedata.github.io/nmdc-schema/gold_path_field/)
10. [principal_investigator](https://microbiomedata.github.io/nmdc-schema/principal_investigator/)
11. [execution_resource](https://microbiomedata.github.io/nmdc-schema/execution_resource/)
12. [url](https://microbiomedata.github.io/nmdc-schema/url/)
13. [display_order](https://microbiomedata.github.io/nmdc-schema/display_order/)
14. [git_url](https://microbiomedata.github.io/nmdc-schema/git_url/)
15. [file_size_bytes](https://microbiomedata.github.io/nmdc-schema/file_size_bytes/)
16. [md5_checksum](https://microbiomedata.github.io/nmdc-schema/md5_checksum/)

**Comment by turbomam** [comment]
```yaml
name: attribute
description: 'A attribute of a biosample. Examples: depth, habitat, material. For
  NMDC, attributes SHOULD be mapped to terms within a MIxS template'
from_schema: https://w3id.org/nmdc/nmdc
aliases:
- field
- property
- template field
- key
- characteristic
rank: 1000
abstract: true
alias: attribute
range: string
```
