### ISSUE TITLE
when are shared elements allowed? what about in OWL?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1419]
for @aclum esp
- #1334

**Comment by turbomam** [comment]
add 

```yaml
slots:
  test_slot1:
    range: TestEnum
  test_slot2: { }
  test_slot3: { }
  SharedName: { }
```

```shell
make squeaky-clean all test
```
