### ISSUE TITLE
remove or act on # comments in schema files

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1440]
- [ ] https://github.com/microbiomedata/nmdc-schema/issues/1439
- [ ] audit schema files for `comments`, `notes` and `todos` that require action

----

## src/schema/basic_slots.yaml

```yaml
  #  nucleic_acid_concentration:
  #    range: InstrumentValue
```
```yaml
  instrument_name:
    description: >-
      The name of the instrument that was used for processing the sample.
#    range: instrument_name_enum
```

```yaml
#enums:
#  instrument_name_enum:
#    todos:
#      - remove "21T Agilent"
#    permissible_values:
#      - 12T_FTICR_B
#      - 15T_FTICR
#      - 21T Agilent
#      - 21T_Agilent
#      - Agilent_GC_MS_01
#      - Illumina HiSeq
#      - Illumina HiSeq 2500
#      - Illumina HiSeq 2500-1TB
#      - Illumina NextSeq 550
#      - Illumina NovaSeq
#      - Illumina NovaSeq S4
#      - QExactHF03
#      - QExactP02
#      - VOrbiETD04
```

## src/schema/core.yaml

```yaml
  ProcessedSample:
    is_a: MaterialEntity
    title: Processed Sample
    slots:
      - biomaterial_purity
      - dna_absorb1
      - dna_concentration
      - external_database_identifiers
    #      - nucleic_acid_concentration
```

```yaml
  #  InstrumentValue:
  #    is_a: AttributeValue
  #    slots:
  #      - has_unit
  #      - has_numeric_value
  #      - instrument_name
```

```yaml
  #  Instrument:
  #    is_a: NamedThing
  #    aliases:
  #      - device
  #    description: >-
  #      A material entity that is designed to perform a function in a scientific investigation, but is not a reagent[OBI].
  #    exact_mappings:
  #      - OBI:0000485
  #    slot_usage:
  #      id:
  #        required: true
  #        structured_pattern:
  #          syntax: "{id_nmdc_prefix}:inst-{id_shoulder}-{id_blade}{id_version}{id_locus}"
  #          interpolated: true
```

## src/schema/external_identifiers.yaml

```yaml
  mgnify_analysis_identifiers:
    is_a: analysis_identifiers
    notes:
      - 'removed pattern: "^mgnify:MGYA[0-9]+$" ## TODO https://github.com/bioregistry/bioregistry/issues/109'
```

## src/schema/prov.yaml

```yaml
  started_at_time:
    #    range: datetime
```

```yaml
  ended_at_time:
    #    range: datetime
```

```yaml
  used:
    domain: Activity
    # some Instrument slot usages, but those require a CURIE, not a bare string
    # this is being used more like instrument_name
    mappings:
      - prov:used
```

## src/schema/workflow_execution_activity.yaml

```YAML
  MetaproteomicsAnalysisActivity:
    is_a: WorkflowExecutionActivity
    in_subset:
      - workflow subset
    slots:
      - has_peptide_quantifications
    slot_usage:
      used:
        # range: Instrument
```

```yaml
  NomAnalysisActivity:
    is_a: WorkflowExecutionActivity
    in_subset:
      - workflow subset
    slots:
      - has_calibration
    slot_usage:
      used:
        range: string
        #        range: Instrument
```
