### ISSUE TITLE
remove vestiges of  `Instrument` and `InstrumentValue` from schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1443]
there was a comment on `MetaproteomicsAnalysisActivity` and `NomAnalysisActivity` _in  `src/schema/workflow_execution_activity.yaml`_ that `Instrument` would be a good `slot_usage` `range` for `used`

cc @anastasiyaprymolenna 

----

```yaml
Instrument:
  is_a: NamedThing
  aliases:
    - device
  description: >-
    A material entity that is designed to perform a function in a scientific investigation, but is not a reagent[OBI].
  exact_mappings:
    - OBI:0000485
  slot_usage:
    id:
      required: true
      structured_pattern:
        syntax: "{id_nmdc_prefix}:inst-{id_shoulder}-{id_blade}{id_version}{id_locus}"
        interpolated: true
```
