### ISSUE TITLE
nmdc.yaml # comment cleanup

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1448]
```yaml
  FieldResearchSite:
    aliases:
      - research plot
    description: A site, outside of a laboratory, from which biosamples may be collected.
    is_a: Site
    title: Field Research Site
    comments:
      - Provides grouping of biosamples at level that's more specific than belonging
        to the same study
      - be very clear that this could be part of a larger site
      - In Bioscales, one might say that rhizosphere soil and bulk soil from around
        the same plant were obtained at the same site. In this case, the site would
        correspond to one tree.
      - "might correspond to GOLD's identifier on a page like https://gold.jgi.doe.gov/biosample?id=Gb0305833"
    slots:
      - cur_vegetation
      - elev
      - geo_loc_name
      - habitat # gold term... enumerated values?
```

```yaml
    unique_keys:
      samp_name_unique_key:
        unique_key_slots:
          - samp_name # id is already required to be unique because it is the identifier in Biosample's parent class, NamedThing
```

```yaml
      ## MIXS slots
      #      - horizon
      #      - microbial_biomass
      #      - microbial_biomass_meth
      #      - previous_land_use_meth
      #      - samp_collect_device
      #      - texture
      #      - texture_meth
```

```yaml
      ## EMSL slots
      - bulk_elect_conductivity

      ## bioscales slots
```

```yaml
      ## Related IDs
      #- insdc_sra_ena_study_identifiers
```

```yaml
  StatusEnum:
    permissible_values:
      pass: { }
      fail: { }
  #      accepted: { }
  #      archived: { }
  #      deleted: { }
  #      draft: { }
  #      rejected: { }
  #      submitted: { }
  #      superseded: { }
  #      withdrawn: { }
```

```yaml
  LibraryTypeEnum:
    # start using the right case for enum names
    # we have other slots which need a DNA or RNA answer, so maybe we should make this enum name more generic
```

```yaml
  env_package:
    aliases:
      - environmental package
    notes:
      - no longer in MIxS as of 6.0?
    description:
      MIxS extension for reporting of measurements and observations obtained
      from one or more of the environments where the sample was obtained. All environmental
      packages listed here are further defined in separate subtables. By giving the
      name of the environmental package, a selection of fields can be made from the
      subtables and can be reported
    in_subset:
      - mixs extension
    is_a: attribute
    range: TextValue
  #      pattern: '[air|built environment|host\-associated|human\-associated|human\-skin|human\-oral|human\-gut|human\-vaginal|hydrocarbon
  #        resources\-cores|hydrocarbon resources\-fluids\/swabs|microbial mat\/biofilm|misc
  #        environment|plant\-associated|sediment|soil|wastewater\/sludge|water]'
```

```yaml
  duration: # or could be a ISO8601 period string
    range: QuantityValue
    description: The elapsed time of an activity.
    examples:
      - value:
          has_numeric_value: 2
          has_unit: hours
```
