### ISSUE TITLE
`ProtocolExecution` is no longer present in main branch

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1487]
@anastasiyaprymolenna 

I'll see if I can dig it back up form previous commits.

I'm not too concerned even if I can't find it. I'm pretty sure I can mentally reconstruct it

**Comment by eecavanna** [comment]
I asked ChatGPT:

```
What is a Git command I can use to determine the commit in which a given string was 
first introduced into a repository?
```

Its response was:

```shell
git log -S'your_string' --all --pickaxe-regex --reverse --pretty=format:"%h %ad %s"
```

I ran that command on my local clone of `nmdc-schema` and the output pointed to this commit:

https://github.com/microbiomedata/nmdc-schema/commit/d314f1af6fca9f45fb59c48eb7b23d8d3fe50111#diff-7b7f5304564f280f4600b8c155fd4eea51e7851f92966d69d8b847ed8e0d368eR51

I noticed it is on a non-`main` branch. I don't know whether that branch has ever been merged into `main`.

**Comment by anastasiyaprymolenna** [comment]
ProtocolExecution has never been in the main branch. This was work in the 907 brand that has never been merged in.

**Comment by turbomam** [comment]
Thanks @eecavanna and @anastasiyaprymolenna 

From the **not-yet deleted** https://github.com/microbiomedata/nmdc-schema/compare/issue-907-metabolink-mergeprep branch

Here's the content that we may want to add back in:

```yaml
  ProtocolExecution:
    is_a: PlannedProcess
    description: A PlannedProces that has PlannedProcess parts. Can be used to represent the case of someone following a Protocol
    slots:
      - has_part
      - protocol_execution_category
      - protocol_link
```

```yaml
  protocol_execution_category:
    domain: ProtocolExecution
    range: ProtocolCategoryEnum
    required: true
  sample_operation_set:
    mixins:
      - object_set
    domain: Database
    range: SampleOperation
  protocol_execution_set:
    mixins:
      - object_set
    domain: Database
    range: ProtocolExecution
```

```yaml
  ProtocolCategoryEnum:
    description: The possible protocols that may be followed.
    permissible_values:
      MPLEx:
```
