### ISSUE TITLE
global replace OmicsProcessing with DataGeneration

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1515]
Replace all records of OmicsPrcessing with DataGeneration.

**Comment by turbomam** [comment]
leave OmicsProcessing as an alias

**Comment by turbomam** [comment]
- cloned git@github.com:microbiomedata/berkeley-schema-fy24.git, which i s based on
- opened in PyCharm
- built poetry environment
- currently running `make squeaky-clean all test`

**Comment by turbomam** [comment]
### Omitting `slots` and `slot_usages`

```yaml
  DataGeneration:
    aliases:
      - OmicsProcessing
      - assay
      - omics assay
      - sequencing project
      - experiment
    is_a: PlannedProcess
    in_subset:
      - sample subset
    description: >-
      The methods and processes used to generate omics data from a biosample or organism.
    alt_descriptions:
      embl.ena:
        An experiment contains information about a sequencing experiment including
        library and instrument details.
    broad_mappings:
      - OBI:0000070
      - ISA:Assay
```
