### ISSUE TITLE
Change `part_of` slot from `WorkflowExecution`(`Activity`) class to have range `WorkflowChain`

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1547]
`part_of` is redundant with `was_informed_by` on the `WorkflowExecution` class.

**Comment by mslarae13** [comment]
@brynnz22  @mbthornton-lbl is this still going to be worked on?

**Comment by brynnz22** [comment]
Yes, I believe so.

**Comment by mbthornton-lbl** [comment]
This is already done as part of an earlier commit - this is the part_of slot_usage from berkley-schema-fy24.main:

```
      part_of:
        required: true
        description: >-
          The WorkflowChain that this WorkflowExecution is part of
        range: WorkflowChain
        multivalued: false
```
