### ISSUE TITLE
add `feature_category` slot to replace `type` as used by FunctionalAnnotation and GenomeFeature

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1592]
```yaml
  feature_category:
    range: ControlledIdentifiedTermValue
    description: A Sequence Ontology term that describes the category of a feature
    comments:
      - FunctionalAnnotation and GenomeFeature had commented-out 'type' slot_usages that had been intended
        to capture SO terms
```
