### ISSUE TITLE
Replacements required for AFO mappings in nmdc-schema including 

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1626]
The [Allotrope Foundation Ontologies](https://www.ebi.ac.uk/ols4/ontologies/afo) may have some useful content, but their upper modeling is inconsistent with the other ontologies we use, and their URIs use an unusual syntax.

```yaml
  DissolvingProcess:
    class_uri: 'nmdc:DissolvingProcess'
    aliases:
      - Solubilization
    description: >
      A mixing step where a soluble component is mixed with a liquid component.
    exact_mappings:
      - AFO:/process#AFP_0000112
    contributors:
      - ORCID:0009-0001-1555-1601 #Anastasiya Prymolenna
      - ORCID:0000-0002-1368-8217 #Yuri Corilo
    is_a: MaterialProcessing
    slots:
      - solvent
      - solubilizing_agent
      - duration
      - temperature
    slot_usage:
      id:
        required: true
        structured_pattern:
          syntax: "{id_nmdc_prefix}:dispro-{id_shoulder}-{id_blade}{id_version}{id_locus}"
          interpolated: true
```

@anastasiyaprymolenna @corilo would [CHMO:0002773 dissolving](https://www.ebi.ac.uk/ols4/ontologies/chmo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHMO_0002773) be an acceptable mapping for DissolvingProcess above?
