### ISSUE TITLE
Permissible values require descriptions and or meanings

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1627]
For example, the `rna_sample_format_enum`

The `meaning`s metaslot has a CURIe range and should be populated with an external term that has the same meaning, just like mappings on most other terms. These terms must come from vocabularies that are already known to the nmdc-scherma, via a `prefixes` block.

 ```yaml
  rna_sample_format_enum:
    from_schema: https://example.com/nmdc_dh
    permissible_values:
      10 mM Tris-HCl: { }
      DNAStable: { }
      Ethanol: { }
      Low EDTA TE: { }
      MDA reaction buffer: { }
      PBS: { }
      Pellet: { }
      RNAStable: { }
      TE: { }
      Water: { }
      Gentegra-DNA: { }
      Gentegra-RNA: { }
```
