### ISSUE TITLE
`eluent_introduction_category` modeling broken in latest backmerge

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1972]
@brynnz22 @anastasiyaprymolenna @kheal 

I did a back-merge from `nmdc-schema` into `berkeley-schema-fy24` this morning and accidentally pushed it into `berkeley-schema-fy24` `main` instead of a branch

Everything seems fine except for anything related to `eluent_introduction_category`

Are we still going to use that after the remodeling @kheal did yesterday?

If so, I could use some help getting that to work again. I'll take responsibility for digging up the last good state of the two repos.

**Comment by turbomam** [comment]
problematic example data files:

- Database-interleaved.yaml
- Database-mass-spectrometry.yaml
- Database-mass_spectrometry_gc.yaml
- MassSpectrometry-NOM.yaml

**Comment by turbomam** [comment]
Actually, this seems unrelated to `eluent_introduction_category`

> ```
> [ERROR] [src/data/problem/Database-mass-spectrometry.yaml/0] 'nmdc:dgms-99-zUCd5N' does not match '^(nmdc):(dgns|omprc)-([0-9][a-z]{0,6}[0-9])-([A-Za-z0-9]{1,})(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$' in /data_generation_set/0/id
> [ERROR] [src/data/problem/Database-mass-spectrometry.yaml/0] 'nmdc:dgms-99-zUCd5x' does not match '^(nmdc):(dgns|omprc)-([0-9][a-z]{0,6}[0-9])-([A-Za-z0-9]{1,})(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$' in /data_generation_set/1/id
> ```

**Comment by turbomam** [comment]
`nmdc:dgms-99-zUCd5N` and `nmdc:dgms-99-zUCd5x` are both asserted to be of type `nmdc:MassSpectrometry`

[MassSpectrometry](https://microbiomedata.github.io/berkeley-schema-fy24/MassSpectrometry/) `is_a` [DataGeneration](https://microbiomedata.github.io/berkeley-schema-fy24/DataGeneration/) and has

```yaml
slot_usage:
  id:
    name: id
    domain_of:
    - NamedThing
    structured_pattern:
      syntax: '{id_nmdc_prefix}:(dgms|omprc)-{id_shoulder}-{id_blade}{id_version}{id_locus}'
      interpolated: true
```
