### ISSUE TITLE
`berkeley-schema-fy24`: id slot_usage resulting in badly minted IDs

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-schema#2122]
In `berkeley-schema-fy24`, some of the syntax declarations on ids of classes result in extra parentheses during minting on the berkeley-schema nmdc runtime.  This results in badly minted ids for instances of new classes.

TLDR.  
Actions to take to fix this bug:
- [x] Shorten id typecodes to adhere to nmdc standards and update CONTRIBUTING guide accordingly (in berkeley schema repo)
- [x] Remove extraneous parentheses for ids on definition of `MassSpectrometryConfiguration` and  `ChromatographyConfiguration` (in berkeley schema repo)
- microbiomedata/nmdc-runtime#592

For example:
```
  ChromatographyConfiguration:
    is_a: Configuration
    class_uri: nmdc:ChromatographyConfiguration
    slot_usage:
      id:
        structured_pattern:
          syntax: "{id_nmdc_prefix}:(chrocon)-{id_shoulder}-{id_blade}$"
          interpolated: true
```
Example minted ID of `ChromatographyConfiguration` = nmdc:(chrocon)-14-bwmbj819.  
That can be fixed easily with a schema change by removing the () around chrocon, as classes without this result in well minted IDs (example `Instrument` class mints to nmdc:inst-14-3p938v35 for example)

**However** instances of `DataGeneration`:`NucleotideSequencing` are less easily fixed
```
  NucleotideSequencing:
    class_uri: nmdc:NucleotideSequencing
    is_a: DataGeneration
    slot_usage:
      id:
        structured_pattern:
          syntax: "{id_nmdc_prefix}:(dgns|omprc)-{id_shoulder}-{id_blade}$"
          interpolated: true
```
Example minted ID of `NucleotideSequencing` = nmdc:(dgms|omprc)-14-2204gm61. 🙀 
My guess is that the minter doesn't know which to choose of those options (dgms|omprc).
My understanding is that we will need to keep the flexibility on the id prefixes for referential integrity, so I do not have a solution forward to fixing this example.

I am not sure _where_ to fix this - on the schema or in the minter or some combination of both?

@brynnz22, @eecavanna, @aclum, @dwinston, @turbomam - I'm actually not sure who all needs to be in on this conversation since it's a schema:minter intersection issue.
