### ISSUE TITLE
`env_package` should have a range of an Enum

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#2167]
The `env_package` slot in the schema should have the range of an Enum, with the list of permissible values constructed using the value of `<EnvPackage>` in https://www.ncbi.nlm.nih.gov/biosample/docs/packages/?format=xml (so we are aligned with NCBI as well)

**Comment by aclum** [comment]
@mslarae13 @pkalita-lbl please comment on if you are okay with these proposed changes wrt submission portal. This will streamline the nmdc mongo to ncbi xml code. Otherwise we'll need a mapping table.

**Comment by turbomam** [comment]
I would also be open to the permissible values coming from MIxS Extensions, but am totally happy with @sujaypatil96's suggestion for the values NCBI calls `<EnvPackage>` on their submission specifications, and  `package` in their downloadable Biosample XML records

**Comment by turbomam** [comment]
We need an official mapping between the NCBI namespace, the MIxS namespace, and any variable used in code like submission-schema and nmdc-server

**Comment by pkalita-lbl** [comment]
Broadly speaking that seems okay. As far as the submission portal is concerned, `env_package` is _not_ a slot that we have users fill out for each sample metadata record. Instead it gets derived based on their choice in the Environmental Package screen:

![image](https://github.com/user-attachments/assets/de3f10b6-5121-4456-9de0-81a0a20bb189)

The submission portal's frontend code already maintains a crazy mapping between human readable names and `env_package` values and `submission-schema` class names and more. If we could _reduce_ (or at least not increase) the level of that craziness that would be nice.

**Comment by turbomam** [comment]
The commented-out pattern removed in https://github.com/microbiomedata/nmdc-schema/pull/3133 listed the valid values:

`air`, `built environment`, `host-associated`, `human-associated`, `human-skin`, `human-oral`, `human-gut`, `human-vaginal`, `hydrocarbon resources-cores`, `hydrocarbon resources-fluids/swabs`, `microbial mat/biofilm`, `misc environment`, `plant-associated`, `sediment`, `soil`, `wastewater/sludge`, `water`

These are the MIxS environmental packages and should become the permissible values of the enum that replaces the TextValue range.

**Comment by mslarae13** [comment]
this I think was for something more complex than just the environmental extension.
I think the request here included the checklist.. so package

But @sujaypatil96 should confirm and clarify if this is still needed.

**Comment by turbomam** [comment]
I'm bumping this based on a discussion @sujaypatil96 and I had today about adding "Metagenome.environmental.1.0" as a permissible value for this proposed enum, based on the work he and @aclum are doing to ingest the Microflora Danica data from NCBI. I don't think that NCBI package can be directly mapped to any of the MIxS-biased values that we have been talking about above.

**Comment by turbomam** [comment]
@aclum  what are your preferences about 
- keeping "Metagenome.environmental.1.0" in a enum-ranged `env_package` for the MFD Biosamples or similar NCBI imports
- inferring something more MIxS-like from other fields on those Biosamples (like Soil, Water, etc)
- switching to modeling that retains the NCBI-asserted value but adds something normalized too


I assume the MFD "Metagenome.environmental.1.0" is coming from `Package.content`, which is populated in 100% of NCBI Biosamples.  There are about 200 unique values.

All Biosamples also populate `Models.Model[].content` with about 250 less standardized values

Only about 0.6% of Biosamples assert a `Attributes.Attribute[]` where `attribute_name = "env_package"`. MFD doesn't use it.

**Comment by turbomam** [comment]
<details>
<summary>My proposed env_package enum</summary>


```yaml
  EnvironmentalPackageEnum:
    description: >-
      Controlled value for the environmental package (MIxS environmental
      extension) a biosample belongs to. Becomes the range of the required
      env_package slot. MetagenomeEnvironmental is the honest value for NCBI
      records that declared only the generic metagenome package; the plan is to
      infer a more specific extension for those over time, not to leave them
      unclassified.
    permissible_values:

      Soil:
        description: MIxS soil environmental package.
        structured_aliases:
          - {literal_form: "soil",             predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "soil_data",        predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}
          - {literal_form: "MIMS.me.soil.6.0", predicate: RELATED_SYNONYM, source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
        notes: Realized prod also carries the raw value "ENVO:00001998" (soil); 100 biosamples.

      Water:
        description: MIxS water environmental package.
        structured_aliases:
          - {literal_form: "water",             predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "water_data",        predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}
          - {literal_form: "MIMS.me.water.6.0", predicate: RELATED_SYNONYM, source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}

      Sediment:
        description: MIxS sediment environmental package.
        structured_aliases:
          - {literal_form: "sediment",             predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "sediment_data",        predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}
          - {literal_form: "MIMS.me.sediment.6.0", predicate: RELATED_SYNONYM, source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}

      Air:
        description: MIxS air environmental package.
        structured_aliases:
          - {literal_form: "air",      predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "air_data", predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      PlantAssociated:
        description: MIxS plant-associated environmental package.
        structured_aliases:
          - {literal_form: "plant-associated",      predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "plant_associated_data", predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      HostAssociated:
        description: MIxS host-associated environmental package.
        structured_aliases:
          - {literal_form: "host-associated",      predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "Host-associated",      predicate: EXACT_SYNONYM,   source: https://api.microbiomedata.org/nmdcschema/biosample_set}
          - {literal_form: "host_associated_data", predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      MicrobialMatBiofilm:
        description: MIxS microbial mat / biofilm environmental package.
        structured_aliases:
          - {literal_form: "microbial mat/biofilm", predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "microbial mat_biofilm", predicate: EXACT_SYNONYM,   source: https://github.com/microbiomedata/nmdc-runtime}
          - {literal_form: "biofilm_data",          predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      BuiltEnvironment:
        description: MIxS built environment environmental package.
        structured_aliases:
          - {literal_form: "built environment", predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "built_env_data",    predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}
          - {literal_form: "built_env",         predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/nmdc-server}

      MiscellaneousNaturalOrArtificialEnvironment:
        description: MIxS miscellaneous natural or artificial environment package.
        structured_aliases:
          - {literal_form: "miscellaneous natural or artificial environment", predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "misc environment", predicate: RELATED_SYNONYM, source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "misc_envs_data",   predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      WastewaterSludge:
        description: MIxS wastewater / sludge environmental package.
        structured_aliases:
          - {literal_form: "wastewater/sludge",      predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "wastewater_sludge_data", predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}
          - {literal_form: "wastewater_sludge",      predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/nmdc-server}
        notes: In submission-schema and nmdc-server; absent from the nmdc-runtime EnvironmentPackage enum.

      HydrocarbonResourcesCores:
        description: MIxS hydrocarbon resources - cores environmental package.
        structured_aliases:
          - {literal_form: "hydrocarbon resources-cores", predicate: EXACT_SYNONYM,   source: https://github.com/microbiomedata/nmdc-runtime}
          - {literal_form: "hcr_cores_data",              predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      HydrocarbonResourcesFluidsSwabs:
        description: MIxS hydrocarbon resources - fluids / swabs environmental package.
        structured_aliases:
          - {literal_form: "hydrocarbon resources-fluids_swabs", predicate: EXACT_SYNONYM,   source: https://github.com/microbiomedata/nmdc-runtime}
          - {literal_form: "hcr_fluids_swabs_data",             predicate: RELATED_SYNONYM, source: https://github.com/microbiomedata/submission-schema}

      MetagenomeEnvironmental:
        description: >-
          NCBI "metagenome or environmental" package. Used when the source
          declared only the generic NCBI package and no specific MIxS extension.
          A real, required value (not an unclassified placeholder); the plan is to
          infer a more specific extension for these records over time. No known
          MIxS/ENVO CURIE points to it, so it has no meaning by design.
        structured_aliases:
          - {literal_form: "Metagenome.environmental.1.0", predicate: EXACT_SYNONYM,   source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
          - {literal_form: "Metagenome or environmental",  predicate: RELATED_SYNONYM, source: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/}
```

</details>
