### ISSUE TITLE
Add `aliases` / `mappings` / `annotations` for GOLD platform / model CV

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#2174]
Objective:

Store mappings recorded in this [issue comment](https://github.com/microbiomedata/nmdc-runtime/pull/656#issuecomment-2316086950) as "mappings" on [InstrumentVendorEnum](https://microbiomedata.github.io/berkeley-schema-fy24/InstrumentVendorEnum/) and [InstrumentModelEnum](https://microbiomedata.github.io/berkeley-schema-fy24/InstrumentModelEnum/).

Decide the LinkML construct to be used to store these mappings, i.e., whether to use `aliases`, `mappings` or `annotations`.

<hr />

Implications:

This is required for the work being done to "migrate" the GOLD translator to make it conformant with the berkeley schema. See https://github.com/microbiomedata/nmdc-runtime/pull/656

**Comment by aclum** [comment]
MVP here should be Illumina models, more work is needed across the project for pacbio and oxford.

HiSeq
HiSeq-HO
HiSeq-Rapid
HiSeq-1TB
HiSeq2500
MiSeq
NextSeq-MO
NextSeq-HO
X10
NovaSeq
NovaSeq SP
NovaSeq S4
NovaSeq S2
NovaSeqX 10B
NovaSeqX 25B
NovaSeqX 1.5B

**Comment by turbomam** [comment]
Thanks fro this info, @aclum. Where did you get the controlled vocabulary (so @sujay and I can revisit it in the future)?

I want to move forward quickly on this, but there are at lest two problems:
1. the MVP list of models is really a mixture of instrument names, instruments + kit/flowcell names and instrument families. We need to be consistent, preferably aligning to an ontology like OBI
2. we have an impedance mismatch: berkeley-schema-fy24 represents instruments and models. GOLD seems to represent platforms, families, models and more. We need to be intentional about how we align those two spaces with different levels.

I'm sure we can work this out. @sujaypatil96 and I have been consulting the Illumine support page and OBI's representation of sequencing instruments. We'll have more insights soon.

Remember, the schema is frozen, so that may effect turn around time!

**Comment by aclum** [comment]
use structured aliases
https://linkml.io/linkml-model/latest/docs/structured_aliases/

**Comment by aclum** [comment]
The CV for GOLD comes from a query of an internal JGI database table. I updated this to a table to include what it should map to. I hope this will inform if we should use structured aliases vs adding a slot to Instrument. My preference is to use the enums,  since what is in gold is a display and not how JGI names their individual instruments internally. @turbomam @kheal @sujaypatil96

**Comment by turbomam** [comment]
Thanks @aclum . Could you share a rawer form of the instrument values from the GOLD database contents? Maybe unique values (with or without counts).

**Comment by turbomam** [comment]
@aclum (or anybody else) can you provide a GOLD study id that includes GOLD sequencing instrumentation information? 

I tried https://gold-ws.jgi.doe.gov/api/v1/projects?projectGoldId=Gp0820739, but that didn't seem to have it

**Comment by turbomam** [comment]
see also
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/247

**Comment by turbomam** [comment]
The instrument vocabular doesn't seem to be included in [GOLD CVs Excel](https://gold.jgi.doe.gov/download?mode=cv_excel) from https://gold.jgi.doe.gov/downloads

I guess that's why you did a database query

**Comment by turbomam** [comment]
see also
- https://microbiomedata.github.io/berkeley-schema-fy24/InstrumentModelEnum/

**Comment by turbomam** [comment]
A `StructuredAlias` solution would look something like this:

```yaml
name: InstrumentModelEnum
permissible_values:
  hiseq_2500:
    meaning: OBI:0002002
    aliases:
    - Illumina HiSeq 2500
    structured_aliases:
      - literal_form: Illumina HiSeq-1TB
        alias_contexts:
        -  https://gold.jgi.doe.gov/
        alias_predicate: RELATED_SYNONYM
      - literal_form: Illumina HiSeq2500
        alias_predicate: EXACT_SYNONYM
        alias_contexts:
        -  https://gold.jgi.doe.gov/
```

**Comment by turbomam** [comment]
I recommend providing mappings from the GOLD strings to both the `InstrumentModelEnum` and the `InstrumentVendorEnum`

If we used `StructuredAlias`es like that, then the ETL application **might** have to iterate through all of the structured aliases in both enums to find the appropriate vendor and model values.

Or the ETL could pre-generate a data structure, in memory, in the opposite direction like

```yaml
- gold: Illumina HiSeq-1TB
  vendor_pv: Illumina
  model_pv: hiseq_2500
- gold: Illumina HiSeq2500
  vendor_pv: Illumina
  model_pv: hiseq_2500
```
