### ISSUE TITLE
Broken link: w3id link to MIxS terms is broken

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2255]
The schema contains this (this is an excerpt):

```yaml
  geo_loc_name:
    # ...
    from_schema: http://w3id.org/mixs/terms
    # ...
```
> Source: [mixs.yaml](https://github.com/microbiomedata/nmdc-schema/blob/a5c3f4e7fe221b01d24151e536bfe00cbeb3ac19/src/schema/mixs.yaml#L4418C18-L4418C44)

When I visit that URL (i.e. `http://w3id.org/mixs/terms`), I end up at an error page (at `https://genomicsstandardsconsortium.github.io/mixs/terms`):

![image](https://github.com/user-attachments/assets/6d2dea75-ba32-47af-938d-2fcd704173cd)

There are 500+ occurrences of the string `http://w3id.org/mixs/terms` in that `mixs.yaml` file.
