### ISSUE TITLE
Find replacements for GENEPIO and OMIT mappings if possible and/or define prefixes

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2258]
Thanks for providing these mappings, @aculm. 

`GENEPIO` and  `OMIT` aren't defined as prefixes yet. That's an error condition but it isn't super visible in the standard build process. We haven't used them before (although GENEPIO appears in an un-checked example in the mixs.yaml file). We should be conservative about adding new namespaces to the schema, especially if they aren't clearly authorities on the concepts being addressed.

Examples:

```yaml
  members_id:
    range: string
    multivalued: true
    description: Names of the contigs that make up a metagenome-assembled genome.
    close_mappings:
      - GENEPIO:0100596
```

and

```yaml
  num_5s:
    description: Number of 5s seqeuences detected, a subunit of ribosomes.
    range: integer
    minimum_value: 0
    broad_mappings:
      - OMIT:0013248
```
