### ISSUE TITLE
'GOLD sample identifiers' description '[''identifiers for corresponding sample in GOLD'']' after gen-yaml

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#228]
```yaml
  GOLD sample identifiers:
    name: GOLD sample identifiers
    definition_uri: https://microbiomedata/meta/GOLD_sample_identifiers
    description: '[''identifiers for corresponding sample in GOLD'']'
```

Because the description is a list element in `src/schema/external_identifiers.yaml`?

```yaml
  GOLD sample identifiers:
    is_a: sample identifiers
    mixins:
      - GOLD identifiers
    pattern: "^GOLD:Gb[0-9]+$"
    multivalued: true
    description:
      - identifiers for corresponding sample in GOLD
    examples:
      - value: https://identifiers.org/gold:GbTODO
```
