### ISSUE TITLE
'env_local_scale' description contains double quotes

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#229]
As in

> '"In this field, report the entity or entities which are in your
      sample or specimenUs local vicinity and which you believe have significant causal
      influences on your sample or specimen. Please use terms that are present in
      ENVO and which are of smaller spatial grain than your entry for env_broad_scale.
      Format (one term): termLabel [termID]; Format (multiple terms): termLabel [termID]|termLabel
      [termID]|termLabel [termID]. Example: Annotating a pooled sample taken from
      various vegetation layers in a forest consider: canopy [ENVO:00000047]|herb
      and fern layer [ENVO:01000337]|litter layer [ENVO:01000338]|understory [01000335]|shrub
      layer [ENVO:01000336]. If needed, request new terms on the ENVO tracker, identified
      here: http://www.obofoundry.org/ontology/envo.html"'

Because double quotes were used in addition to `>-` ?

```yaml
  env_local_scale:
    aliases:
      - local environmental context
    description: >-
       "In this field, report the entity or entities which are in your sample or specimenUs local vicinity and which you believe have significant causal influences on your sample or specimen. Please use terms that are present in ENVO and which are of smaller spatial grain than your entry for env_broad_scale. Format (one term): termLabel [termID]; Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID]. Example: Annotating a pooled sample taken from various vegetation layers in a forest consider: canopy [ENVO:00000047]|herb and fern layer [ENVO:01000337]|litter layer [ENVO:01000338]|understory [01000335]|shrub layer [ENVO:01000336]. If needed, request new terms on the ENVO tracker, identified here: http://www.obofoundry.org/ontology/envo.html"
    multivalued: false
    is_a: attribute
    range: controlled term value  ## syntax: {termLabel} {[termID]}
    pattern: ".* \\S+:\\S+"
    mappings:
      - mixs:env_local_scale
    in_subset:
      - environment
```

**Comment by turbomam** [comment]
in `src/schema/mixs.yaml`

if I fix this in that file, will it be overwritten by some Perl script @cmungall has spoken of?

**Comment by turbomam** [comment]
I tried replacing `description: >-\s+"` with `description: "` but `pipenv run gen-yaml src/schema/nmdc.yaml` said

> File "<file>", line 1150, column 5
expected <block end>, but found '<scalar>'

> File "<file>", line 1152, column 81

because of double quotes in?

```yaml
  votu_seq_comp_appr:
    aliases:
      - vOTU sequence comparison approach
    description: "Tool and thresholds used to compare sequences when computing ""species-level"" vOTUs"
    multivalued: false
    is_a: attribute
    range: text value  ## syntax: {software};{version};{parameters}
    mappings:
      - mixs:votu_seq_comp_appr
    in_subset:
      - sequencing
```
