### ISSUE TITLE
remove enums that aren't used by any slots according to ``

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2298]
doesn't require a migrator?

- freq_clean_enum
- organism_count_enum
- plant_growth_med_enum
- samp_md_enum

**Comment by turbomam** [comment]
There are slots that share names with these enums, like `samp_md`, 'sample measured depth', which currently has a `QuantityValue` range.

I have no idea how that relates to these PVs. Too bad there's no annotations.

```yaml
  samp_md_enum:
    from_schema: http://w3id.org/mixs/terms
    permissible_values:
      DF: {}
      RT: {}
      KB: {}
      MSL: {}
      other: {}
```

Possibly related: https://en.wikipedia.org/wiki/Depth_in_a_well
