### ISSUE TITLE
problematic 'slot_url's and ''s from gen-yaml

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#230]
https://microbiomedata/schema/mixs/ph

```yaml
  identifier:
    name: identifier
    definition_uri: https://microbiomedata/meta/identifier
    from_schema: https://microbiomedata/schema
    slot_uri: nmdc:identifier
    owner: biosample
    domain_of:
    - biosample
    range: string
```
- it seems like some LinkML tools can convert `https://microbiomedata/meta/identifier` to `nmdc:identifier` since the `nmdc` prefix is defined as `https://microbiomedata/meta/`. But I haven't seen `https://microbiomedata/schema` magically rendered in a prefixed  form. 
- Also, these URLs don't resolve as web links
