### ISSUE TITLE
create a `GeoLocationNameValue` class with substructure

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2305]
as a future replacement `range` for 

```yaml
name: geo_loc_name
description: The geographical origin of the sample as defined by the country or sea
  name followed by specific region name. Country or sea names should be chosen from
  the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (http://purl.bioontology.org/ontology/GAZ)
title: geographic location (country and/or sea,region)
examples:
- value: 'USA: Maryland, Bethesda'
keywords:
- geographic
- location
slot_uri: MIXS:0000010
range: string
required: true
pattern: '^([^\s-]{1,2}|[^\s-]+.+[^\s-]+): ([^\s-]{1,2}|[^\s-]+.+[^\s-]+), ([^\s-]{1,2}|[^\s-]+.+[^\s-]+)$'
structured_pattern:
  syntax: '^{text}: {text}, {text}$'
  interpolated: true
  partial_match: true
```

**Comment by turbomam** [comment]
```yaml
is_a: AttributeValue
slots:
- nation_or_sea
- admin_level_1
- locale
```
