### ISSUE TITLE
Invalid `collection_time` and `collection_time_inc` examples in final schema

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-schema#2314]
When the `collection_time` and `collection_time_inc` slots are defined in `src/schema/portal_mixs_inspired.yaml` they have reasonable looking examples:

```yaml
examples:
  - value: 13:33
  - value: 13:33:55
```

However after those values shoot through the build pipeline somehow they come out the other end (in `nmdc_schema/nmdc_materialized_patterns.yaml`) like this:

```yaml
examples:
  - value: '813'
  - value: '48835'
```

I assume that this is caused by some YAML parser's implicit identification of the original values as a partial datetimes and then stringifying those values elsewhere. The safest thing to do is probably to define them as strings in `src/schema/portal_mixs_inspired.yaml` so nothing munges them.
