### ISSUE TITLE
'examples' from GOLD sample identifiers: https://identifiers.org/gold:GbTODO

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#233]

**Comment by turbomam** [comment]
Could we either enter a real example GOLD sample identifier, or remove the example and add a to-do?

**Comment by turbomam** [comment]
in `src/schema/external_identifiers.yaml`

```yaml
  GOLD sample identifiers:
    is_a: sample identifiers
    mixins:
      - GOLD identifiers
    pattern: "^GOLD:Gb[0-9]+$"
    multivalued: true
    description:
      - identifiers for corresponding sample in GOLD
    examples:
      - value: https://identifiers.org/gold:GbTODO
```
