### ISSUE TITLE
annotations for mixs_env_triad_field are not getting picking up

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2395]
Annotations are missing from linkml documentation, nmdc.py and nmdc_materialized_patterns.yaml with nmdc-schema version 5.11.1.

Expected behavior: LinkML documenation for this slot https://microbiomedata.github.io/nmdc-schema/mixs_env_triad_field shows annotations.  See documentation page for https://microbiomedata.github.io/nmdc-schema/gold_path_field/

Original work done in https://github.com/microbiomedata/nmdc-schema/issues/2119

**Comment by turbomam** [comment]
Version https://github.com/microbiomedata/nmdc-schema/releases/tag/v11.5.1, right?

**Comment by turbomam** [comment]
```shell
grep gold_path_field nmdc_schema/nmdc_materialized_patterns.yaml  -C 30
```

With a little trimming: 

```yaml
  gold_path_field:
    name: gold_path_field
    annotations:
      tooltip:
        tag: tooltip
        value: GOLD Ecosystem Classification paths describe the surroundings from
          which an environmental sample or an organism is collected.
        annotations:
          source:
            tag: source
            value: https://gold.jgi.doe.gov/ecosystem_classification

  ecosystem:
    name: ecosystem
    description: An ecosystem is a combination of a physical environment (abiotic
      factors) and all the organisms (biotic factors) that interact with this environment.
      Ecosystem is in position 1/5 in a GOLD path.
    comments:
    - The abiotic factors play a profound role on the type and composition of organisms
      in a given environment. The GOLD Ecosystem at the top of the five-level classification
      system is aimed at capturing the broader environment from which an organism
      or environmental sample is collected. The three broad groups under Ecosystem
      are Environmental, Host-associated, and Engineered. They represent samples collected
      from a natural environment or from another organism or from engineered environments
      like bioreactors respectively.
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - https://gold.jgi.doe.gov/help
    is_a: gold_path_field

  ecosystem_category:
    name: ecosystem_category
    description: Ecosystem categories represent divisions within the ecosystem based
      on specific characteristics of the environment from where an organism or sample
      is isolated. Ecosystem category is in position 2/5 in a GOLD path.
    comments:
    - The Environmental ecosystem (for example) is divided into Air, Aquatic and Terrestrial.
      Ecosystem categories for Host-associated samples can be individual hosts or
      phyla and for engineered samples it may be manipulated environments like bioreactors,
      solid waste etc.
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - https://gold.jgi.doe.gov/help
    is_a: gold_path_field

  ecosystem_type:
    name: ecosystem_type
    description: Ecosystem types represent things having common characteristics within
      the Ecosystem Category. These common characteristics based grouping is still
      broad but specific to the characteristics of a given environment. Ecosystem
      type is in position 3/5 in a GOLD path.
    comments:
    - The Aquatic ecosystem category (for example) may have ecosystem types like Marine
      or Thermal springs etc. Ecosystem category Air may have Indoor air or Outdoor
      air as different Ecosystem Types. In the case of Host-associated samples, ecosystem
      type can represent Respiratory system, Digestive system, Roots etc.
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - https://gold.jgi.doe.gov/help
    is_a: gold_path_field

  ecosystem_subtype:
    name: ecosystem_subtype
    description: Ecosystem subtypes represent further subdivision of Ecosystem types
      into more distinct subtypes. Ecosystem subtype is in position 4/5 in a GOLD
      path.
    comments:
    - Ecosystem Type Marine (Environmental -> Aquatic -> Marine) is further divided
      (for example) into Intertidal zone, Coastal, Pelagic, Intertidal zone etc. in
      the Ecosystem subtype category.
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - https://gold.jgi.doe.gov/help
    is_a: gold_path_field

  specific_ecosystem:
    name: specific_ecosystem
    description: Specific ecosystems represent specific features of the environment
      like aphotic zone in an ocean or gastric mucosa within a host digestive system.
      Specific ecosystem is in position 5/5 in a GOLD path.
    comments:
    - Specific ecosystems help to define samples based on very specific characteristics
      of an environment under the five-level classification system.
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - https://gold.jgi.doe.gov/help
    is_a: gold_path_field

```

**Comment by turbomam** [comment]
```shell
grep mixs_env_triad_field nmdc_schema/nmdc_materialized_patterns.yaml  -C 30
```

```yaml
  env_broad_scale:
    name: env_broad_scale
    annotations:
      expected_value:
        tag: expected_value
        value: The major environment type(s) where the sample was collected. Recommend
          subclasses of biome [ENVO:00000428]. Multiple terms can be separated by
          one or more pipes.
      tooltip:
        tag: tooltip
        value: The biome or major environmental system where the sample or specimen
          originated. Choose values from subclasses of the 'biome' class [ENVO:00000428]
          in the Environment Ontology (ENVO). For host-associated or plant-associated
          samples, use terms from the UBERON or Plant Ontology to describe the broad
          anatomical or morphological context
    description: 'Report the major environmental system the sample or specimen came
      from. The system(s) identified should have a coarse spatial grain, to provide
      the general environmental context of where the sampling was done (e.g. in the
      desert or a rainforest). We recommend using subclasses of EnvO’s biome class:  http://purl.obolibrary.org/obo/ENVO_00000428.
      EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS'
    title: broad-scale environmental context
    examples:
    - value: oceanic epipelagic zone biome [ENVO:01000035]
    from_schema: https://w3id.org/nmdc/nmdc
    aliases:
    - broad-scale environmental context
    is_a: mixs_env_triad_field
    string_serialization: '{termLabel} {[termID]}'
    slot_uri: MIXS:0000012
    range: ControlledIdentifiedTermValue
    multivalued: false

  env_local_scale:
    name: env_local_scale
    annotations:
      expected_value:
        tag: expected_value
        value: Environmental entities having causal influences upon the entity at
          time of sampling.
      tooltip:
        tag: tooltip
        value: The specific environmental entities or features near the sample or
          specimen that significantly influence its characteristics or composition.
          These entities are typically smaller in scale than the broad environmental
          context. Values for this field should be countable, material nouns and must
          be chosen from subclasses of BFO:0000040 (material entity) that appear in
          the Environment Ontology (ENVO). For host-associated or plant-associated
          samples, use terms from the UBERON or Plant Ontology to describe specific
          anatomical structures or plant parts.
    description: 'Report the entity or entities which are in the sample or specimen’s
      local vicinity and which you believe have significant causal influences on your
      sample or specimen. We recommend using EnvO terms which are of smaller spatial
      grain than your entry for env_broad_scale. Terms, such as anatomical sites,
      from other OBO Library ontologies which interoperate with EnvO (e.g. UBERON)
      are accepted in this field. EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS.'
    title: local environmental context
    examples:
    - value: litter layer [ENVO:01000338]
    from_schema: https://w3id.org/nmdc/nmdc
    aliases:
    - local environmental context
    is_a: mixs_env_triad_field
    string_serialization: '{termLabel} {[termID]}'
    slot_uri: MIXS:0000013
    range: ControlledIdentifiedTermValue
    multivalued: false

  env_medium:
    name: env_medium
    annotations:
      expected_value:
        tag: expected_value
        value: The material displaced by the entity at time of sampling. Recommend
          subclasses of environmental material [ENVO:00010483].
      tooltip:
        tag: tooltip
        value: The predominant environmental material or substrate that directly surrounds
          or hosts the sample or specimen at the time of sampling. Choose values from
          subclasses of the 'environmental material' class [ENVO:00010483] in the
          Environment Ontology (ENVO). Values for this field should be measurable
          or mass material nouns, representing continuous environmental materials.
          For host-associated or plant-associated samples, use terms from the UBERON
          or Plant Ontology to indicate a tissue, organ, or plant structure
    description: 'Report the environmental material(s) immediately surrounding the
      sample or specimen at the time of sampling. We recommend using subclasses of
      ''environmental material'' (http://purl.obolibrary.org/obo/ENVO_00010483). EnvO
      documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS
      . Terms from other OBO ontologies are permissible as long as they reference
      mass/volume nouns (e.g. air, water, blood) and not discrete, countable entities
      (e.g. a tree, a leaf, a table top).'
    title: environmental medium
    examples:
    - value: soil [ENVO:00001998]
    from_schema: https://w3id.org/nmdc/nmdc
    aliases:
    - environmental medium
    is_a: mixs_env_triad_field
    string_serialization: '{termLabel} {[termID]}'
    slot_uri: MIXS:0000014
    range: ControlledIdentifiedTermValue
    multivalued: false

  mixs_env_triad_field:
    name: mixs_env_triad_field
    from_schema: https://w3id.org/nmdc/nmdc

```

**Comment by turbomam** [comment]
in `src/schema/mixs.yaml`

```yaml
  mixs_env_triad_field: null
```

in addition to the successful `is_a: mixs_env_triad_field` statements

**Comment by turbomam** [comment]
```shell
make mixs-yaml-clean
```

**Comment by turbomam** [comment]
```shell
make --dry-run src/schema/mixs.yaml
```

does

```shell
#rm -rf local/mixs_regen/mixs_subset_modified.yaml # triggers complete regeneration
rm -rf local/mixs_regen/*.yaml
rm -rf shuttle-clean.bak
mkdir -p local/mixs_regen
touch local/mixs_regen/.gitkeep
poetry run do_shuttle \
        --recipient_model assets/other_mixs_yaml_files/mixs_template.yaml \
        --config_tsv assets/import_mixs_slots_regardless.tsv \
        --yaml_output local/mixs_regen/mixs_subset.yaml
# switching to TextValue may not add any value. the other range changes do improve the structure of the data.
# ironically changing back to strings for the submission-schema, data harmonizer, submission portal etc.
# may switch source of truth to the MIxS 6.2.2 release candidate
sed 's/quantity value/QuantityValue/' local/mixs_regen/mixs_subset.yaml > local/mixs_regen/mixs_subset_modified.yaml
sed -i.bak 's/range: string/range: TextValue/' local/mixs_regen/mixs_subset_modified.yaml
sed -i.bak 's/range: text value/range: TextValue/' local/mixs_regen/mixs_subset_modified.yaml
grep "^'" assets/yq-for-mixs_subset_modified.txt | while IFS= read -r line ; do echo $line ; eval yq -i $line local/mixs_regen/mixs_subset_modified.yaml ; done
rm -rf local/mixs_regen/mixs_subset_modified.yaml.bak
# inject re-structured cur_land_use_enum
#   using '| cat > ' because yq doesn't seem to like redirecting out to a file
yq eval-all \
        'select(fileIndex==0).enums.cur_land_use_enum = select(fileIndex==1).enums.cur_land_use_enum | select(fileIndex==0)' \
        local/mixs_regen/mixs_subset_modified.yaml assets/other_mixs_yaml_files/cur_land_use_enum.yaml | cat > local/mixs_regen/mixs_subset_modified_inj_land_use.yaml
yq eval-all \
        'select(fileIndex==0).enums.TargetGeneEnum = select(fileIndex==1).enums.TargetGeneEnum | select(fileIndex==0)' \
        local/mixs_regen/mixs_subset_modified_inj_land_use.yaml assets/other_mixs_yaml_files/TargetGeneEnum.yaml | cat > local/mixs_regen/mixs_subset_modified_inj_TargetGeneEnum.yaml
yq -i '.slots.target_gene.range = "TargetGeneEnum"' local/mixs_regen/mixs_subset_modified_inj_TargetGeneEnum.yaml
yq eval-all \
        'select(fileIndex==0).slots.env_broad_scale.annotations.tooltip = select(fileIndex==1).slots.env_broad_scale.annotations.tooltip | select(fileIndex==0)' \
        local/mixs_regen/mixs_subset_modified_inj_TargetGeneEnum.yaml assets/other_mixs_yaml_files/nmdc_mixs_env_triad_tooltips.yaml | cat > local/mixs_regen/mixs_subset_modified_inj_env_broad_scale_alt_description.yaml
yq eval-all \
        'select(fileIndex==0).slots.env_local_scale.annotations.tooltip = select(fileIndex==1).slots.env_local_scale.annotations.tooltip | select(fileIndex==0)' \
        local/mixs_regen/mixs_subset_modified_inj_env_broad_scale_alt_description.yaml assets/other_mixs_yaml_files/nmdc_mixs_env_triad_tooltips.yaml | cat > local/mixs_regen/mixs_subset_modified_inj_env_local_scale_alt_description.yaml
yq eval-all \
        'select(fileIndex==0).slots.env_medium.annotations.tooltip = select(fileIndex==1).slots.env_medium.annotations.tooltip | select(fileIndex==0)' \
        local/mixs_regen/mixs_subset_modified_inj_env_local_scale_alt_description.yaml assets/other_mixs_yaml_files/nmdc_mixs_env_triad_tooltips.yaml | cat > local/mixs_regen/mixs_subset_modified_inj_env_medium_alt_description.yaml
yq eval-all \
        'select(fileIndex==0).slots.mixs_env_triad_field = select(fileIndex==1).slots.mixs_env_triad_field | select(fileIndex==0)' \
        local/mixs_regen/mixs_subset_modified_inj_env_medium_alt_description.yaml assets/other_mixs_yaml_files/mixs_env_triad_field_slot.yaml | cat > local/mixs_regen/mixs_minus_1.yaml
mv local/mixs_regen/mixs_minus_1.yaml src/schema/mixs.yaml
rm -rf local/mixs_regen/mixs_subset_modified.yaml.bak
```

**Comment by turbomam** [comment]
```shell
make src/schema/mixs.yaml
```

**Comment by turbomam** [comment]
```shell
make squeaky-clean all test
```

**Comment by turbomam** [comment]
```shell
make squeaky-clean
make mixs-yaml-clean
```

**Comment by turbomam** [comment]
Try commenting out most of mixs_env_triad_field_slot.yaml except for 

```yaml
    abstract: true
    range: ControlledIdentifiedTermValue
``` 

```shell
make src/schema/nmdc.yaml
make squeaky-clean all test
```

**Comment by turbomam** [comment]
That worked

Reintroduce the followin ginto `mixs_env_triad_field_slot.yaml` and rebuild

```yaml
    see_also:
      - https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS
    created_by:
      - orcid:0000-0002-5004-3362 # Alicia Clum
    contributors:
      - orcid:0000-0001-9076-6066 # Mark Andrew Miller
```
