### ISSUE TITLE
remove commented `StatusEnum.permissible_values`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2398]
```yaml
  StatusEnum:
    permissible_values:
      pass: { }
      fail: { }
  #      accepted: { }
  #      archived: { }
  #      deleted: { }
  #      draft: { }
  #      rejected: { }
  #      submitted: { }
  #      superseded: { }
  #      withdrawn: { }
```
