### ISSUE TITLE
biosample processing and omics processing should not be in a subclass relationship

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#24]
biosample processing is documented to be a process that takes samples as inputs and generates samples as outputs; ie sample->sample

```yaml
  biosample processing:
    is_a: named thing
    description: >-
      A process that takes one or more biosamples as inputs and generates one or as outputs.
      Examples of outputs include samples cultivated from another sample or data objects created by instruments runs.
    slots:
      - has input
    slot_usage:
      has input:
        range: biosample
```

we can map this to to [material processing in OBI](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000094)

this can be used to represent graphs of arbitrary depths of processes on samples, from treatments through to subsampling, making aliquots. In practice these graphs may be flat especially for retrospective samples

omics_processing doesn't have a sample as output - it generates omics data, i.e sample->data. Yet it is a subclass of biosample processing

```yaml
 omics processing:
    is_a: biosample processing
    in_subset: 
      - sample subset
    description: >-
      The methods and processes used to generate omics data from a biosample or organism.
    comments:
      - The IDs for objects coming from GOLD will have prefixes gold:GpNNNN
    slots:
      - part of
      - has output
      - omics type
    slot_usage:
      id:
        description: >-
          The primary identifier for the omics processing. E.g. GOLD:GpNNNN
      name:
        description: >-
          A human readable name or description of the omics processing.
      alternate identifiers:
        description: >-
          The same omics processing may have distinct identifiers in different databases (e.g. GOLD and EMSL, as well as NCBI)
      part of:
        range: study
      has output:
        range: data object
```

I think this can be mapped to [assay in OBI](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000070)

I don't think this is quite coherent, if OP inherits from BP then it should inherit the condition that the output is a sample

It may be more straightforward to have these be siblings

If we want we can have a grouping class for both of these
