### ISSUE TITLE
remove commented `env_package.pattern` or apply as an enum

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2400]
Would require alignment with some standard, like MIxS Extension names

Would require a migration

```yaml
  env_package:
    aliases:
      - environmental package
    notes:
      - no longer in MIxS as of 6.0?
    description:
      MIxS extension for reporting of measurements and observations obtained
      from one or more of the environments where the sample was obtained. All environmental
      packages listed here are further defined in separate subtables. By giving the
      name of the environmental package, a selection of fields can be made from the
      subtables and can be reported
    range: TextValue
  #      pattern: '[air|built environment|host\-associated|human\-associated|human\-skin|human\-oral|human\-gut|human\-vaginal|hydrocarbon
  #        resources\-cores|hydrocarbon resources\-fluids\/swabs|microbial mat\/biofilm|misc
  #        environment|plant\-associated|sediment|soil|wastewater\/sludge|water]'
```
