### ISSUE TITLE
pattern in `insdc_secondary_sample_identifiers` is incompatible with suggested prefix

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2401]
this works/is resolvable

```yaml
  insdc_biosample_identifiers:
    pattern: "^biosample:SAM[NED]([A-Z])?[0-9]+$"
    examples:
    - value: biosample:SAMEA5989477
    - value: biosample:SAMD00212331
```

but `insdc_secondary_sample_identifiers` says 

```yaml
  insdc_secondary_sample_identifiers:
    pattern: "^biosample:(E|D|S)RS[0-9]{6,}$"
    examples:
      - value: insdc.sra:DRS166340
```

these are the prefix expansions

```yaml
  biosample: 'https://bioregistry.io/biosample:'
  insdc.sra: "https://bioregistry.io/insdc.sra:"
```

these resolve
- https://bioregistry.io/biosample:SAMEA5989477
- https://bioregistry.io/biosample:SAMD00212331

this would resolve
- https://bioregistry.io/insdc.sra:DRS166340

but this doesn't
- https://bioregistry.io/biosample:DRS166340
