### ISSUE TITLE
`src/schema/core.yaml` uses unresolvable `NCBI`-prefixed mappings for taxonomic ranks

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2403]
```yaml
  gtdbtk_species:
    description: Taxonomic genus assigned by GTDB-Tk.
    see_also: 
      - doi:10.1093/bioinformatics/btz848
    range: string
    exact_mappings:
      - NCBITaxon:species
```

where

```
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
```

http://purl.obolibrary.org/obo/NCBITaxon_species does not resolve
