### ISSUE TITLE
`src/schema/core.yaml` has a `UUID`-prefixes example. What is NMDC's preferred prefix for UUIDs?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2405]
```yaml
  examples:
    - value: IGSN:AU1243
    - value: UUID:24f1467a-40f4-11ed-b878-0242ac120002
```
