### ISSUE TITLE
some `structured_pattern`s result in materialized `patterns` that have two caret anchors `^^`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2410]
11 cases in  in generated  `nmdc_schema/nmdc_materialized_patterns.schema.json`, like 

```json
  "instrument_used": {
      "description": "What instrument was used during DataGeneration or MaterialProcessing.",
      "items": {
          "pattern": "^^(nmdc):inst-([0-9][a-z]{0,6}[0-9])-([A-Za-z0-9]{1,})$",
          "type": "string"
      }
```

This may be related to the use of carets in the https://linkml.io/linkml-model/latest/docs/settings/ 

```yaml
settings:
  id_nmdc_prefix: ^(nmdc)
  id_shoulder: ([0-9][a-z]{0,6}[0-9])
  id_blade: ([A-Za-z0-9]{1,})
  id_version: (\.[0-9]{1,})
  id_locus: (_[A-Za-z0-9_\.-]+)?$
```

Maybe we need to explicitly use the `partial_match` slot in a https://linkml.io/linkml-model/latest/docs/PatternExpression/. I don' think we have asserted it anywhere yet.

**Comment by kheal** [comment]
This is the direct result of having an extra "^" in the .yaml `structured_pattern`

i.e. on `DataObject`:
```
    slot_usage:
      was_generated_by:
        structured_pattern:
          syntax: "^{id_nmdc_prefix}:(wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc)-{id_shoulder}-{id_blade}{id_version}$|^{id_nmdc_prefix}:(omprc|dgms|dgns)-{id_shoulder}-{id_blade}$"
          interpolated: true
        range: DataEmitterProcess
```
