### ISSUE TITLE
eliminate `any_of` from schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2418]
this will make it easier to work with the schema and it's data in SQL and OWL/RDF

only appearing in class rules now!

see 
- #2417 

###  MassSpectrometry.rules[1].preconditions.slot_conditions.eluent_introduction_category

```yaml
  any_of:
  - equals_string: liquid_chromatography
  - equals_string: gas_chromatography
```

###  Doi.rules[0].preconditions.slot_conditions.doi_category

```yaml
  any_of:
  - equals_string: dataset_doi
  - equals_string: award_doi
```

**Comment by turbomam** [comment]
just write out ass a larger number of independent rules?

**Comment by turbomam** [comment]
The `doi_category` rule's description isn't comprehensive any more

>  If doi_category is a publication_doi, then doi_provider is not required. Otherwise, doi_provider is required.

```yaml
  DoiCategoryEnum:
    permissible_values:
      award_doi:
      dataset_doi:
      publication_doi:
      data_management_plan_doi:
```
