### ISSUE TITLE
mixs as a submodule

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#291]
for moving away from the old static-ish MIxS 5 [mixs.yaml](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml) 

MIxS isn't available through w3id yet, and the LinkML YAML files aren't bundled with the PyPI package yet:

```shell
pip show -f mixs-linkml
```

> Name: mixs-linkml
Version: 0.1.1
Summary: A LinkML (https://linkml.io/) model of the MIxS standard (https://gensc.org/mixs/)
Home-page: 
Author: GSC
Author-email: 
License: CC0
Location: /Users/MAM/mixs_pypi_test/venv/lib/python3.9/site-packages
Requires: linkml, mkdocs, pandas
Required-by: 
Files:
  mixs_linkml-0.1.1.dist-info/INSTALLER
  mixs_linkml-0.1.1.dist-info/LICENSE
  mixs_linkml-0.1.1.dist-info/METADATA
  mixs_linkml-0.1.1.dist-info/RECORD
  mixs_linkml-0.1.1.dist-info/REQUESTED
  mixs_linkml-0.1.1.dist-info/WHEEL
  release/__init__.py
  release/__pycache__/__init__.cpython-39.pyc
  release/graphql/mixs.graphql
  release/jsonld/mixs.context.jsonld
  release/jsonld/mixs.jsonld
  release/jsonschema/mixs.schema.json
  release/mixs.py
  release/owl/mixs.owl.ttl
  release/prefixmap/mixs.yaml
  release/protobuf/mixs.proto
  release/shacl/mixs.shacl.ttl
  release/shex/mixs.shex
  release/sqlschema/mixs.sql

**Comment by turbomam** [comment]
- _16s_recover
- _16s_recover_software
- bin name
- bin quality
- chem_treatment_method
- completeness
- contamination
- env_package
- extreme_salinity
- gene count
- gtdbtk class
- gtdbtk domain
- gtdbtk family
- gtdbtk genus
- gtdbtk order
- gtdbtk phylum
- gtdbtk species
- health_disease_stat
- heat_system_deliv_meth
- host_blood_press_diast
- host_blood_press_syst
- ihmc_ethnicity
- investigation_type
- mixs_url
- nose_mouth_teeth_throat_disord
- num 16s
- num 23s
- num 5s
- num tRNA
- number of contig
- organism_count_qpcr_info
- pres_animal
- resp_part_matter
- room_architec_element
- room_moist_damage_hist
- samp_collection_point
- shading_device_water_mold
- submitted_to_insdc
- tot_nitro_content_meth
- tvdss_of_hcr_pressure
- votu_class_appr
- votu_db
- votu_seq_comp_appr
- water_content_soil_meth
- water_production_rate
-

**Comment by turbomam** [comment]
But these are the only lost MIxS slots that the current nmdc-schema associates with biosamples:
`['env_package', 'tot_nitro_content_meth', 'water_content_soil_meth']`

And none of those even appear in the mongodb biosample_set

**Comment by turbomam** [comment]
Here's a starting point for discussing a new MIxS 6 dynamic import into the nmdc-schema:

[`src/schema/mixs_6_for_nmdc.yaml`, in the `issue-291-mixs-submod` branch](https://github.com/microbiomedata/nmdc-schema/blob/issue-291-mixs-submod/src/schema/mixs_6_for_nmdc.yaml)

Filenames, schema names and IDs etc can all be changed.

Is this sufficient for declaring that a slot comes from MIxS?

```yaml
slots:
  SLOTNAME:
    from_schema: http://w3id.org/mixs/terms
```

**Comment by turbomam** [comment]
get rid of empty examples etc.

**Comment by turbomam** [comment]
compare ranges between old MIxS 5 and new MIxS 6 files, especially looking for things like quantity value

deepdiff?

**Comment by turbomam** [comment]
funny looking `wall_texture_enum` PVs

**Comment by turbomam** [comment]
`env_package` from MIxS 5-based `src/schema/mixs.yaml` sure looks like an enum

```yaml
range: text value
pattern: '[air|built environment|host\-associated|human\-associated|human\-skin|human\-oral|human\-gut|human\-vaginal|hydrocarbon
  resources\-cores|hydrocarbon resources\-fluids\/swabs|microbial mat\/biofilm|misc
  environment|plant\-associated|sediment|soil|wastewater\/sludge|water]'
```
