### ISSUE TITLE
document has_calibration in metabolomics analysis activity

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#304]
I'm comparing our schema to mzML, we have

```yaml
  metabolomics analysis activity:
    is_a: workflow execution activity
    in_subset: 
      - workflow subset
    slot_usage:
      used:
        range: instrument
        multivalued: false
        description: >-
          The instrument used to collect the data used in the analysis
      has metabolite quantifications:
        range: metabolite quantification
        multivalued: true
      has calibration:
        description: >-
          TODO: Yuri to fill in
```

what goes in the calibration field?

currently the range of this field is the default range (string) - but it looks like it should be a non-inlined reference to another object?

Example data from API:

```json
  "results": [
    {
      "type": "nmdc:MetabolomicsAnalysisActivity",
      "has_input": [
        "emsl:output_646802"
      ],
      "has_output": [
        "nmdc:c0f8177e881e53d2fd9305597be7a400"
      ],
      "id": "nmdc:8969f454c3944f1eac9da499fb950a18",
      "ended_at_time": "2021-01-08T11:51:33Z",
      "execution_resource": "EMSL-RZR",
      "git_url": "https://github.com/microbiomedata/metaMS",
      "has_calibration": "emsl:output_646437",
      "started_at_time": "2021-01-08T11:51:33Z",
      "used": "Agilent_GC_MS",
      "was_informed_by": "emsl:646802",
      "has_metabolite_quantifications": [
        {
          "highest_similarity_score": 0.55246881446802,
          "metabolite_quantified": "chebi:17724",
          "alternative_identifiers": [
            "kegg:C01026",
            "cas:1118-68-9"
          ]
        },

```    

But we don't seem to have emsl:output_646437 in the database?
