### ISSUE TITLE
NMDC documents should refer to NMDC schema terms by their names or their titles

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#339]
Shared documentation and even informal communication between NMDC team members should refer to NMDC schema terms by their `name`s or their `title`s 

When team members have been referring to terms by something else (because the something else may be memorable or informative), that something else could be added to the term's `aliases`, or to the descriptive annotations on that term.

Consider the MIxS term below, from https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml. It has `name` = 'abs_air_humidity' and `title` = 'absolute air humidity'. If it has been helpful to call that 'dankness', we could add that as an alias. There should never be a case when team members refer to a term by soemthign that can't be found verbatim in the schema. @cmungall , @sujaypatil96 and @turbomam can help with this.

```yaml
slots:
  abs_air_humidity:
    name: abs_air_humidity
    aliases:
    - absolute air humidity
    annotations:
      expected_value:
        tag: expected_value
        value: measurement value
      preferred_unit:
        tag: preferred_unit
        value: gram per gram, kilogram per kilogram, kilogram, pound
      occurrence:
        tag: occurrence
        value: '1'
    description: Actual mass of water vapor - mh20 - present in the air water vapor
      mixture
    title: absolute air humidity
    examples:
    - value: 9 gram per gram
    from_schema: http://w3id.org/mixs/terms
    source: http://w3id.org/mixs/terms
    see_also:
    - https://github.com/microbiomedata/nmdc-schema/blob/issue-291-mixs-submod/util/rebuild_mixs_yaml.py
    is_a: attribute
    slot_uri: MIXS:0000122
    multivalued: false
    range: quantity value
```
