### ISSUE TITLE
Add slots to database class to capture versioning

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#35]
As part of the ETL, add versioning info to the database class. I have already created some stubs for this:
```yaml
database:
...
      slot_usage:
      nmdc schema version:  <-- pulled from the nmdc.yaml file; I have a util to get this.
        description: >-
            TODO
      date created:  <-- date the database was created
        description: >-
            TODO
      etl software version: <-- requires versioning of our etl scripts
        description: >-
            TODO
```

Do we need others? @dehays @cmungall @dwinston @jeffbaumes @jbeezley
