### ISSUE TITLE
change decimal degree's base type from float to decimal

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#350]

**Comment by turbomam** [comment]
discuss with @cmungall

**Comment by turbomam** [comment]
What kinds of interchanges could cause `45.000000`  to be converted to `45`

Do we care if that did happen

**Comment by turbomam** [comment]
Check for the distribution of decimal place counts in MongoDB

Try some round tripe exercises with different sources and sinks including Data Portal

Close this issue unless it can be tied to an actionable mechanism and fix

If we do find an problem, this GH issue should probably be moved to the repo that owns the problem

**Comment by turbomam** [comment]
Note that the `latitude` and `longitude` slots use this custom type as their range:

```yaml
  decimal_degree:
    name: decimal_degree
    description: A decimal degree expresses latitude or longitude as decimal fractions.
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - https://en.wikipedia.org/wiki/Decimal_degrees
    base: float
    uri: xsd:decimal
```
