### ISSUE TITLE
enumerate institutions like EMSL and normalize existing values

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#352]
What are the permissible values?

Where are they being collected in the submission portal?

CC @SamuelPurvine @mslarae13

**Comment by SamuelPurvine** [comment]
So, currently, the values that should be enumerated would be
- Joint Genome Institute
- University of California, San Diego
- Environmental Molecular Sciences Laboratory

Montana and you would be the ones to know where in the submission portal it is, though your question implies we aren't collecting submitting institution as a value?

I didn't manage to capture the web link Chris put in the zoom chat the other day regarding where "we" might look to find the official names of institutions, but using such a list to populate the enumerations for the institutions would make the most sense to me...

**Comment by turbomam** [comment]
src/schema/nmdc.yaml in https://github.com/microbiomedata/nmdc-schema/releases/tag/v5.0.4 contains some institution enums

still need to 
- [ ] set range of (omics processing).processing_institution.omics to processing_institution_enum
- [ ] re-merge and release
- [ ] do a change sheet to update MongoDB
- [ ] write some tests (step 0!)

```yaml
processing_institution_enum:
  name: processing_institution_enum
  comments:
  - This will become the range of processing_institution.omics processing
  - use ROR meanings like https://ror.org/0168r3w48 for UCSD
  from_schema: NMDC_enums_roundtrip
  permissible_values:
    University of California, San Diego:
      text: University of California, San Diego
      meaning: https://ror.org/0168r3w48
    Joint Genome Institute:
      text: Joint Genome Institute
      meaning: https://ror.org/04xm1d337
    Environmental Molecular Sciences Laboratory:
      text: Environmental Molecular Sciences Laboratory
      meaning: https://ror.org/04rc0xn13
      comments:
      - replaces Environmental Molecular Science Laboratory
      - replaces Environmental Molecular Sciences Lab
```
