### ISSUE TITLE
use sample_link (or a subproperty of that?) to relate samples to sudies

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#383]
I.e. stop saying that a sample is part of a study.

From [src/schema/portal/sample_id.yaml](https://github.com/microbiomedata/nmdc-schema/blob/9a994b8fee5c4464ec1897ea3b8fe4d753a2c841/src/schema/portal/sample_id.yaml#L48-L65):

```yaml
  sample_link:
    name: sample_link
    description: A unique identifier to assign parent-child, subsample, or sibling
      samples. This is relevant when a sample or other material was used to generate
      the new sample.
    title: sample linkage
    comments:
    - 'This field allows multiple entries separated by ; (Examples: Soil collected
      from the field will link with the soil used in an incubation. The soil a plant
      was grown in links to the plant sample. An original culture sample was transferred
      to a new vial and generated a new sample)'
    examples:
    - value: IGSN:DSJ0284
    from_schema: https://example.com/nmdc_dh
    rank: 5
    string_serialization: '{text}:{text}'
    slot_group: Sample ID
    recommended: true
```
