### ISSUE TITLE
slot 'GOLD sample identifiers' is unclear

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#401]
The slot 'GOLD sample identifiers' is identified as used in the class 'study'

The definition of 'GOLD sample identifiers' has value as 'Provide the GOLD study IDs associated with samples for this study.'

Few things

1. That's not a value, isn't that a description?
2. The description fits for study class. BUT, the term says SAMPLE identifiers, which are different from the GOLD study ID.

Which is this supposed to be, how can we update it to be more clear, do we need to add a term?

@turbomam 
@emileyfadrosh 
@sujaypatil96 
@pvangay

**Comment by emileyfadrosh** [comment]
@mslarae13 I think I need some help finding where this is to provide a reasonable response. I don't believe GOLD has a "sample identifier" term, instead there is: GOLD Biosample ID; Biosample name; identifer (see https://gold.jgi.doe.gov/biosample?id=Gb0144001 for example). If 'GOLD sample identifiers' relates to one of the above, we should take the definition directly from GOLD and make sure we are not mixing up study and biosample terms from GOLD. I can do a PR to make an update if you point me to where this is at :)

**Comment by ssarrafan** [comment]
Not assigned to anyone so I'm removing from the Aug sprint. FYI @mslarae13 @emileyfadrosh

**Comment by mslarae13** [comment]
Success here looks like
GOLD sample identifiers slot is "cleaned up"
- The description is made more clear for what it's ACTUALLY identifying.
- If it is meant to be under class study, the slot is re-named to say study, not sample
- If it is meant to capture samples, it is removed from study class & put in biosample class.

**Comment by turbomam** [comment]
This is a good issue, but I don't think much or any action is required. I disagree that slot `GOLD sample identifiers` is used by class `Study`. @mslarae13 , if you have a document that says otherwise, please point me towards it. I hope I didn't do something to confuse you!

First, I searched for all mentions or definitions of `GOLD sample identifiers` in the src/schema directory:

```shell
grep -R 'GOLD sample identifiers' *yaml
```

> external_identifiers.yaml:  GOLD sample identifiers:
nmdc.yaml:      - GOLD sample identifiers
nmdc.yaml:      GOLD sample identifiers:

`GOLD sample identifiers` is defined in `external_identifiers.yaml` and mentioned in `nmdc.yaml`

## Definition

```yaml
  GOLD sample identifiers:
    is_a: sample identifiers
    mixins:
      - GOLD identifiers
    pattern: "^GOLD:Gb[0-9]+$"
    multivalued: true
    description: identifiers for corresponding sample in GOLD
    examples:
      - value: https://identifiers.org/gold:Gb0312930
``` 

You can also see the documentation page at https://microbiomedata.github.io/nmdc-schema/GOLD_sample_identifiers/

_I will be fixing nmdc-schema element names so that we don't have to mentally convert between whitespaces, underscores, camel case, etc. That will have significant impact on MongoDB, possibly the APIs, and the DataPortal._

You will note that `GOLD sample identifiers` inherits all attributes from its ancestors,

- [alternative_identifiers](https://microbiomedata.github.io/nmdc-schema/alternative_identifiers/)
- [external_database_identifiers](https://microbiomedata.github.io/nmdc-schema/external_database_identifiers/)
- [sample_identifiers](https://microbiomedata.github.io/nmdc-schema/sample_identifiers/)

`GOLD sample identifiers` also inherits attributes from the `Gold identifiers` mixin (https://microbiomedata.github.io/nmdc-schema/GOLD_identifiers/), but that doesn't really have many attributes. I think the value of that relationship is mostly organizational.

https://microbiomedata.github.io/nmdc-schema/GOLD_sample_identifiers/ shows that it is only used in one `Applicable Classes`, `[Biosample](https://microbiomedata.github.io/nmdc-schema/Biosample/)`.

I don't see any evidence that slot `GOLD sample identifiers` is used by class [Study](https://microbiomedata.github.io/nmdc-schema/Study/)

Also, "Provide the GOLD study IDs associated with samples for this study." is not the `description` of `GOLD sample identifiers`. It is a `display_hint annotation`, applied in the `slot_usage` block from class `Biosample`:

```yaml
      GOLD sample identifiers:
        annotations:
          display_hint:
            tag: display_hint
            value: >-
              Provide the GOLD study IDs associated with samples for this study.
```

I would say that the actual `description` is pretty good, but possibly not perfect. @mslarae13, let me know if you want to discuss some more and possibly revise this `description`:

> identifiers for corresponding sample in GOLD
