### ISSUE TITLE
add started_at_time, ended_at_time slot to workflow execution activity

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#44]
@cmungall I just noticed that the `workflow execution activity` class does not have `started at time`, `ended at time` slots:
```yaml
workflow execution activity:
    is_a: activity
    in_subset: 
      - workflow subset
    description: >-
      Represents an instance of an execution of a particular workflow
    slots:
      - execution resource
      - git url
      - has input
      - has output
      - type  # custom slot that specifies object type
    slot_usage:
      was associated with:
        required: false
        description: >-
          the agent/entity associated with the generation of the file
        range: workflow execution activity
        inlined: false # allow for strings of IDs
```
However, the data coming from Aim 2 does have the these slots. E.g.:
```json
{
    "id": "nmdc:f2fc8f5aade3092ea97769f0a892d2a9",
    "name": "MAGs activiity 1781_86101",
    "was_informed_by": "gold:Gp0115663",
    "started_at_time": "2021-01-10",
    "ended_at_time": "2021-01-10",
    "type": "nmdc:MAGsAnalysisActivity",
    "execution_resource": "NERSC - Cori",
    "git_url": "https://img.jgi.doe.gov",
    ...
}
```

I think we should add these slots to the schema.

Thoughts?
