### ISSUE TITLE
use linter to standardize element names

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#456]

**Comment by turbomam** [comment]
For example

```yaml
no_empty_title:
  level: warning
permissible_values_format:
  level: disabled
  format: uppersnake
tree_root_class:
  level: disabled
  root_class_name: Container
  validate_existing_class_name: false
recommended:
  level: disabled
  include: [ ]
  exclude: [ ]
no_xsd_int_type:
  level: disabled
no_invalid_slot_usage:
  level: disabled
standard_naming:
  level: warning
  permissible_values_upper_case: false
canonical_prefixes:
  level: warning
  prefixmaps_contexts:
    - merged
```
