### ISSUE TITLE
`data_object_type ` values of "Metagenome Raw Reads" in mongodb

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#487]
there are `data_object_type ` values of "Metagenome Raw Reads" in mongodb, but that is not yet a permissible value in `file type enum`

**Comment by turbomam** [comment]
I am going to add that permissible value and merge it in. @scanon please either add some metadata/annotations to the new permissible value, or delegate that to someone else who has the subject matter knowledge

**Comment by turbomam** [comment]
in `src/schema/nmdc.yaml`

```yaml
  file type enum:
    permissible_values:
      Metagenome Raw Reads:
        todos: add annotations
```
