### ISSUE TITLE
Do we have a way to update the version value in the schema based on a GH tag or vice versa?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#525]

**Comment by eecavanna** [comment]
Within a GitHub Actions workflow YAML file, you can access the Git tag name via: `${{ github.ref_name }}`

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

For example, here's a [workflow step](https://github.com/microbiomedata/nmdc-wordpress-theme/blob/3d17e062f54f0c70cad29fd7d3b4ef35cfad8724/.github/workflows/build.yaml#L15-L18) where a line in a file is being updated (via `sed`) to contain the Git tag:

```yaml
      - name: Update version in `style.css` to match Git tag
        working-directory: ./themes/nmdc
        run: |
          sed -i '/^Version:/s/^Version:.*$/Version: ${{ github.ref_name }}/' ./style.css
```

Here's what the various parts of that command do (with the single quotes omitted here):

|Piece|Explanation|
|--|--|
|`sed -i`| Use `sed` to edit a file in place. |
|`/^Version:/`| Process each line that starts with `Version:`. |
|`s/^Version:.*$/Version: ${{ github.ref_name }}/`| Replace the contents of that line with `Version: ${{ github.ref_name }}`, where `${{ github.ref_name }}` is the Git tag name (e.g. `v1.2.3`). |
|`./style.css`| The file I want to process is `./style.css` file. |
