### ISSUE TITLE
Biosamples relationships sandbox

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#534]
Short term: 
- #518

Long term, how should be relate `Biosample`s to other classes? 
- Though direct slots like `part_of` for Studies?  
- Through reified relationship classes?
- though tag-like enumerations like `biosample_categories`

```yaml
biosample_categories:
  title: Categories the biosample belongs to
  range: biosample_category_enum
  multivalued: true
```
