### ISSUE TITLE
pre-release cleanup

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#549]

**Comment by turbomam** [comment]
- [ ] review .github/workflows
- [ ] assets/3_2_0/nmdc.schema.json and ...4_0_0... used in old Makefile rule 
- [ ] deleted several regenerate-able files from assets. continue to review assets.
- [ ] deleted csv dir
- [ ] deleted .gitmodules and mixs dir
- [ ] deleted doc (not docs!)

```make
DOCS_DIR = docs

gen-doc:
	mkdir -p target/doc
	echo 'forces retention of this directory after rm -rf target/*' > target/doc/placeholder.txt
	$(RUN) gen-doc $(SCHEMA_SRC) --template-directory $(SRC_DIR)/doc-templates -d $(DOCS_DIR)
	cp $(SRC_DIR)/$(DOCS_DIR)/*.md $(DOCS_DIR)
	mkdir -p $(DOCS_DIR)/images
	cp $(SRC_DIR)/$(DOCS_DIR)/images/* $(DOCS_DIR)/images

docserve:
	$(RUN) mkdocs serve

gh-deploy:
# deploy documentation (note: requires documentation is in docs dir)
	$(RUN) mkdocs gh-deploy --force
```

## mkdocs.yml

```yaml
site_name: "NMDC Schema Documentation"

theme:
  name: material
plugins:
  - search
  - mermaid2

docs_dir: docs
site_dir: mkdocs_html

nav:
  - Home: home.md
  - NMDC Schema: index.md
  - NMDC Metadata Standards Documentation:  Metadata_Documentation_Overview.md 
  - NMDC Schema Validation: schema-validation.md
  - Identifiers in NMDC: identifiers.md
  - MIxS Soil Package: NMDC_MIxS_Soil_documentation.md
  - Credits: credits.md
```
