### ISSUE TITLE
Provide class/typecode relations

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#552]
@dwinston will provide a Napa-compliant `id` minting endpoint. He is blocked by needing to know what typecode to include in the `id` for an instance of a particular class.

@sujaypatil96 and I have been working on [two in-schema specifications](https://github.com/microbiomedata/nmdc-schema/blob/bb602c6d12be66850ca49e09b7f36da162e7a9b6/src/schema/nmdc.yaml#L497-L505) for `id`s and typecodes for a subset of classes.

1. `pattern`s, which are part of the current validation. In the slot usage excerpt below, we're saying that the `id` for all instances of class `Biosample` must start with eh characters 'nmdc:'
1. `structured_pattern`s, when combined with `settings`, provide a reusable, symbolic abstraction of regular expression patterns. The expansion and enforcement of  `structured_pattern`s is a work in progress. Nonetheless, **we will be using `structured_pattern`s, and `settings` to communicate the class/typecode pairings. For this issue,I will write a utility that illustrates looking this up[ directly from the schema, without requiring any static helper file.**

```yaml
slot_usage:
  id:
    description: An NMDC assigned unique identifier for a biosample submitted to NMDC.
    required: true
    pattern: '^nmdc:'
    structured_pattern:
      syntax: "{id_nmdc_prefix}:{id_typecode_biosample}-{id_shoulder}-{id_blade}{id_version}{id_locus}"
      interpolated: true
      partial_match: false
```
...

```yaml
settings:
  id_nmdc_prefix: "^(nmdc)"
  id_typecode: "([a-z]{1,6})"
  id_shoulder: "([0-9][a-z]{0,6}[0-9])"
  id_blade: "([A-Za-z0-9]{1,})"
  id_version: "(\\.[A-Za-z0-9]{1,})*"
  id_locus: "(_[A-Za-z0-9_\\.-]+)?$"
  # class to typecode associations
  id_typecode_biosample: "bsm"
  id_typecode_study: "sty"
  id_typecode_biosample_processing: "bsmprc"
  id_typecode_omics_processing: "omprc"
```
