### ISSUE TITLE
Materialize structured patterns, esp for ids

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#592]
We have a potentially misleading combination of `pattern`s and `structured_pattern`s on `id`s, like this for `Biosample`:

```yaml
slot_usage:
  id:
    description: An NMDC assigned unique identifier for a biosample submitted to NMDC.
    required: true
    pattern: '^nmdc:'
    structured_pattern:
      syntax: "{id_nmdc_prefix}:{id_typecode_biosample}-{id_shoulder}-{id_blade}{id_version}{id_locus}"
      interpolated: true
      partial_match: false
```

This was supposed to be a temporary workaround while the ability to materialize `structured_pattern`s was added to `gen-linkml`. Let's do that now.
