### ISSUE TITLE
typecode table should appear right below the identifier page

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#603]
change `mkdocs.yml` to

```yaml
nav:
  - Home: home.md
  - NMDC Schema: index.md
  - NMDC Metadata Standards Documentation: Metadata_Documentation_Overview.md
  - NMDC Schema Validation: schema-validation.md
  - Identifiers in NMDC: identifiers.md
  - Table of Identifier Typecodes for each Class: typecode_table.md
  - MIxS Soil Package: NMDC_MIxS_Soil_documentation.md
  - Credits: credits.md
```
