### ISSUE TITLE
add mixs:samp_mat_process slot for biosamples

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#67]
Add mixs:samp_mat_process slot for biosamples. This will not be handled in the GOLD ETL, though. @dehays and @pvangay will add values during post-etl processing.

**Comment by wdduncan** [comment]
`samp_mat_process` has been added in PR https://github.com/microbiomedata/nmdc-schema/pull/66

Note:  
`samp_mat_process` has a range of `controlled term value`. So, values for this slot/property are to entered using the `has_raw_value` property like so:
```json
{
  "id": "....",
  "type": "nmdc:Biosample",
  "samp_mat_process":  {"has_raw_value": "..."}
  ...
}
```
or by using identifier for an ontology class like so:
```json
{
  "id": "....",
  "type": "nmdc:Biosample",
  "samp_mat_process":  {"has_raw_value": "...", "term": "EFO:0000473"}
  ...
}
```

@cmungall Did you intend for the `term` slot to take a curie or uri for a value?

Here are details of how a `controlled term value` is defined in the schema.
```yaml
attribute value:
    description: >-
      The value for any value of a attribute for a sample. This object can hold both the un-normalized atomic
      value and the structured value
    slots:
      - has raw value
      - was generated by
    slot_usage:
      type:
        description: >-
          An optional string that specified the type of object.
        required: false
  
controlled term value:
    is_a: attribute value
    description: >-
      A controlled term or class from an ontology
    slots:
      - term

term:
    domain: controlled term value
    range: ontology class
    description: >-
      pointer to an ontology class
    slot_uri: rdf:type
    inlined: true

attribute value:
    description: >-
      The value for any value of a attribute for a sample. This object can hold both the un-normalized atomic
      value and the structured value
    slots:
      - has raw value
      - was generated by
    slot_usage:
      type:
        description: >-
          An optional string that specified the type of object.
        required: false
  ```
