### ISSUE TITLE
Typecode assignment for `FieldResearchSite`

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#701]
The [FieldResearchSite](https://microbiomedata.github.io/nmdc-schema/FieldResearchSite/) class is being used in the GOLD NMDC dataset transformation pipeline here: https://github.com/microbiomedata/sample-annotator/pull/113 to pull in values from GOLD and set it on the `collected_from` property in the `Biosample` class object.

Technically, they are ids to and need to be minted as an NMDC Schema compliant id using the minter service. To facilitate that, we need a typecode assigned to the `FieldResearchSite` class.

A comprehensive list of all typecodes can be found here: https://microbiomedata.github.io/nmdc-schema/typecode_table/. The table is statically specified so be sure to check the schema source YAML files in `src/schema` for latest information.

**Comment by turbomam** [comment]
See this note in the typecode_table:

> Last generated 2023-01-12

Its content is static. I may not have made that clear enough. 

The only up-to-date reference on typecodes in the schema itself. 'frsite' has already been assigned as the typecode for `FieldResearchSite` 

```yaml
  FieldResearchSite:
    aliases:
      - research plot
    description: A site, outside of a laboratory, from which biosamples may be collected.
    is_a: Site
    title: Field Research Site
    comments:
      - Provides grouping of biosamples at level that's more specific than belonging
        to the same study
      - be very clear that this could be part of a larger site
      - In Bioscales, one might say that rhizosphere soil and bulk soil from around
        the same plant were obtained at the same site. In this case, the site would
        correspond to one tree.
      - "might correspond to GOLD's identifier on a page like https://gold.jgi.doe.gov/biosample?id=Gb0305833"
    slot_usage:
      id:
        structured_pattern:
          syntax: "{id_nmdc_prefix}:frsite-{id_shoulder}-{id_blade}{id_version}{id_locus}"
          interpolated: true
          partial_match: false
```
