### ISSUE TITLE
Add lacking JGI files to file_type_enums

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc-schema#760]
From JGI we need to be able to import: 

annotation info file `[GOLD_AP]_imgap.info`,  structural annotation stats json `[GOLD_AP]_structural_annotation_stats.json`, and error corrected read data` input.corr.fastq.gz`

Will need to `create file_type_enums` for these.

**Comment by turbomam** [comment]
Sounds good.

See also:
- #711
- #708
- #703

**Comment by Michal-Babins** [comment]
Per @aclum , add README.txt for assembly as Assembly Info File

**Comment by Michal-Babins** [comment]
@turbomam , the README.txt is produced specific to jgi assembly workflow that contains sample metadata, Input Data stats, Read Correction stats, Assembly stats. 

For NMDC I would translate it to activity_id_assembly_info.txt. The README.txt is the jgi annotation: 
```

Assembly Info File:
        text: Assembly Info File
          description: File containing assembly info
          annotations:
            file_name_pattern:
              tag: file_name_pattern
              value: 'README.txt'
```

**Comment by turbomam** [comment]
Ahh. That's great.

BTW, you don't need to make `text` assertions. The key for the permissible value ("Assembly Info File") can be inferred as the `text`. 

And I think @sujaypatil96 suggested using the more compact tag/value notation. Let's start using that now.

So your `Assembly Info File` permissible value for the `file type enum` should be written as

```yaml
Assembly Info File:
  text: Assembly Info File
  description: File containing assembly info
  annotations:
    file_name_pattern:
      tag: file_name_pattern: 'README.txt'
```

I'll do some cleanup on your previous commits. Thanks for contributing to the nmdc-schema!
