### ISSUE TITLE
elev range should show as float, not QuantityValue

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#795]
The rendered documentation for https://w3id.org/nmdc/elev shows its range as https://w3id.org/nmdc/QuantityValue , but it's defined as a float [in the linkml src yaml](https://github.com/microbiomedata/nmdc-schema/blob/v7.4.10/src/schema/nmdc.yaml#L540) and thus as a number [in the materialized json schema](https://github.com/microbiomedata/nmdc-schema/blob/v7.4.10/nmdc_schema/nmdc_materialized_patterns.schema.json#L421). 

This is an issue because I have been using `https://w3id.org/nmdc/<slot>` to debug schema compliance issues in migrating existing metadata, and I want to be able to distinguish between metadata errors and schema errors. It is quite convenient to use `https://w3id.org/nmdc/<slot>` rather than searching around the src yaml directory, as slot definitions live in separate files.

**Comment by turbomam** [comment]
Thanks, @dwinston. 

1. I agree with the convenience of the web pages vs searching through the multiple YAML files. I'm not opposed to merging everything except the MIxS imports into a single nmdc.yaml. I think we have an issue or even an open PR about that.
2. Obviously there shouldn't be a discrepancy between the web-based documentation and the checked-in YAML files. Maybe the  documentation got generated after some change I made to the schema? That's not supposed to happen, but I could check.
3. We have a reasonable technical solutions for asserting whatever type we want for whatever MIxS slot now. Maybe you, @mslarae13, @cmungall and I should review my implementations.
4. So we just need to determine what range we really do want to `elev`! And do that in review of other slots.

**Comment by turbomam** [comment]
- https://github.com/microbiomedata/nmdc-schema/issues/509

**Comment by turbomam** [comment]
_Under construction:_

- how is src/schema/mixs.yaml generated now?
- what MIxS input does it use
- are there any alternative MIxS inputs
- how are modification applied to the MIxS slots for NMDC shcema usage?

---

- how are MIxS slots added to the submission schema now?
- what input is used
- how are modifications applied to the submission schema's 
- how can the nmdc-schema and submission schema's imports and modifications be reconciled?

- https://github.com/microbiomedata/nmdc-schema/blob/main/project.Makefile#L60-L209
- src/schema/mixs.yaml

**Comment by turbomam** [comment]
I reran the `src/schema/mixs.yaml` target and `src/schema/mixs.yaml` has this to say about `elev` now:

```yaml
  elev:
    annotations:
      expected_value:
        tag: expected_value
        value: measurement value
    description: Elevation of the sampling site is its height above a fixed reference point, most commonly the mean sea level. Elevation is mainly used when referring to points on the earth's surface, while altitude is used for points above the surface, such as an aircraft in flight or a spacecraft in orbit.
    title: elevation
    examples:
      - value: 100 meter
    from_schema: http://w3id.org/mixs/terms
    aliases:
      - elevation
    is_a: environment field
    slot_uri: MIXS:0000093
    multivalued: false
    range: QuantityValue
```

That's the verbose syntax, es, wrt annotations, which will need automated tidying later.

Schema and documentation agree on range for elev now. 

Maybe `src/schema/mixs.yaml` should be dded to `make site`, Modifying the Makefile in LinkML cookie cutter repos is discouraged, be we have already done that a few times already
