### ISSUE TITLE
output_read_bases/output_base_count

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#801]
Donny Winston (he/him)
  [12 days ago](https://nmdc-group.slack.com/archives/C04MM663H6J/p1676578798015109)

```
{
    "output_read_bases": "output_base_count",
    "input_read_bases": "input_base_count",
}
```
an appropriate old-to-new-field-names mapping for read_qc_analysis_activity_set? (edited) 

FYI an example validation error on the un-migrated data was:
> nmdc:498a1b67f0b35bc4f059a5de7d5ddb49
data.read_qc_analysis_activity_set[{data__readqcanalysisactivityset_x}] must not contain {'output_read_bases', 'input_read_bases'} properties

This issue has been diagnosed as a bug in the schema wrt slot inheritance.

**Comment by turbomam** [comment]
All of those slots are still at least defined, all in src/schema/workflow_execution_activity.yaml

- input_read_bases
- input_read_count
- output_read_bases
- output_read_count

```yaml
  input_read_count:
    is_a: read_qc_analysis_statistic
    description: >-
      The sequence count number of input reads for QC analysis.
    range: float

  input_base_count:
    is_a: read_qc_analysis_statistic
    description: >-
      The nucleotide base count number of input reads for QC analysis.
    range: float

  output_read_count:
    is_a: read_qc_analysis_statistic
    description: >-
      After QC analysis sequence count number.
    range: float

  output_base_count:
    is_a: read_qc_analysis_statistic
    description: >-
      After QC analysis nucleotide base count number.
    range: float
```

also:

```yaml
  num_input_reads:
    is_a: metagenome_assembly_parameter
    description: >-
      The sequence count number of input reads for assembly.
    range: float
```

**Comment by turbomam** [comment]
They are all assigned to class 

```yaml
  ReadQcAnalysisActivity:
    description: A workflow execution activity that performs quality control on raw Illumina reads including quality trimming, artifact removal, linker trimming, adapter trimming, spike-in removal, and human/cat/dog/mouse/microbe contaminant removal
    title: Read quality control analysis activity
    is_a: WorkflowExecutionActivity
    in_subset:
      - workflow subset
    slots:
      - type
      - input_read_count
      - input_base_count
      - output_read_count
      - output_base_count
```

**Comment by turbomam** [comment]
There is also `slot_usage` on  `ReadQcAnalysisActivity` with some similar sounding terms

```
  ReadQcAnalysisActivity:
    slot_usage:
      input_read_bases:
        range: float
        description: >-
          TODO
      output_read_bases:
        range: float
        description: >-
          TODO
```
