### ISSUE TITLE
Add YesNoEnum to schema, use for dna_dnase and dnase_rna

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#840]
```YAML
  YesNoEnum:
    name: YesNoEnum
    description: replaces DnaDnaseEnum and DnaseRnaEnum
    from_schema: https://example.com/nmdc_submission_schema
    permissible_values:
      'no':
        text: 'no'
      'yes':
        text: 'yes'
```
