### ISSUE TITLE
add schema support for pooling biological samples 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#886]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 6

**RACI**

_Tag people in their roles_
- Responsible: @turbomam, @aclum  
- Accountable: @turbomam 
- Consulted: @mslarae13 
- Informed:

**Describe the the task?**
- Add schema support for a pooling process

Background:
For NEON soil metagenom samples(DP1.10107.001) 3 biological samples are pooled together, generating a DNA library for sequencing from one analytical sample. The nmdc schema current supports biological samples and analytical samples but does not current have a process modeled by which this happens. @turbomam  was going to look at modeling this based on the NEON soil data. 

Soil methods from Quick Start Guide for Soil microbe metagenome sequences (DP1.10107.001) from [soil metagenome data product page ](https://data.neonscience.org/data-products/DP1.10107.001)

Samples are collected and sub-sampled in the field by horizon type (organic and mineral) to a maximum depth of 30 cm, and are pooled at the plot level. Samples are frozen on dry ice in the field and stored in ultralow freezers until they are shipped to an external laboratory for analysis of microbial community structure and functional potential using shotgun metagenomics. 

[DNA extraction SOP](https://data.neonscience.org/api/v0/documents/BMI_dnaExtractionSOP_v7?inline=true)

There is additional DNA extraction and sequencing metadata specific to the analytical sample in the csv files for DP1.10107.001. Files are \*mms_metagenomeDnaExtraction\*csv and \*mms_metagenomeSequencing\*.csv respectively.   Column 13 in \*mms_metagenomeDnaExtraction\*csv, header value `testMethod` lists the DNA extraction protocol used as BMI_dnaExtractionSOP_v3. Column 16 \*mms_metagenomeSequencing*\.csv, header value `labPrepMethod`

For example BMI_metagenomicsSequencingSOP_v3  maps to this [SOP document](https://data.neonscience.org/documents/10179/2431540/BMI_metagenomicsSequencingSOP_v3/f237c337-4756-64c0-23eb-61a783eb71b9?version=1.0)

cc @mslarae13 @anastasiyaprymolenna 

**Criteria for completion**
- main branch of nmdc-schema has a new Class for the pooling process 

**Estimate people time**
- 

**Completion Date (Goal)**
- June 2 

**Target Sprint Start & End Dates**
- Start: May 22 
- End: June 2

**Tag Blocker/Contingent upon issues**

**Comment by turbomam** [comment]
Thanks for the literature links. This is [implemented **very loosely** in the beril-model](https://github.com/beril-model/beril-model/blob/a60d6b2c107c8803224f49f9086e7732c379f83c/src/beril_model/schema/beril_model.yaml#L181-L184) and will be migrated to this schema, as a subclass of [PlannedProcess](https://microbiomedata.github.io/nmdc-schema/PlannedProcess/)

**Comment by turbomam** [comment]
@aclum let's talk about how much we want to put properties onto the pooling process vs how much we want to add new properties to classes like Biosample or AnalyticalSample. I'll  provide some examples soon.

**Comment by aclum** [comment]
I think the ideal outcome is that we create a plannedProcess each for pooling, DNA extraction, and library construction and store the relevant slots with the process. Otherwise the amount of slots will be unruly on either Biosample or Analytical Sample.  I'm curious on how much effort this would take.

**Comment by turbomam** [comment]
Modeling what you described won't take to much effort on top of what I've done today.

I've pasted the induced/reasoned representation of `PlannedProcess` below. You'll see the availability of the `participating_agent` slot, whose range is Agent. My intention was to tie PlannedProcesses to the people or systems that performed them. But Agent may not be a good choice, since it isn't a `NamedThing` doesn't have an `id` slot. We could just change the range to `NamedThing`.

I also pasted an exhaustive instance of a `Database` containing one `Pooling`, meaning it uses all of the associated slots besides `participating_agent`

**Comment by turbomam** [comment]
```yaml
name: PlannedProcess
title: Planned Process
from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
is_a: NamedThing
abstract: true
attributes:
  has_inputs:
    name: has_inputs
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    domain: PlannedProcess
    multivalued: true
    alias: has_inputs
    owner: PlannedProcess
    domain_of:
    - CollectingBiosamplesFromSite
    - PlannedProcess
    range: NamedThing
  has_outputs:
    name: has_outputs
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    domain: PlannedProcess
    multivalued: true
    alias: has_outputs
    owner: PlannedProcess
    domain_of:
    - CollectingBiosamplesFromSite
    - PlannedProcess
    range: NamedThing
  participating_agent:
    name: participating_agent
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    domain: PlannedProcess
    alias: participating_agent
    owner: PlannedProcess
    domain_of:
    - PlannedProcess
    range: Agent
  id:
    name: id
    description: A unique identifier for a thing. Must be either a CURIE shorthand
      for a URI or a complete URI
    notes:
    - 'abstracted pattern: prefix:typecode-authshoulder-blade(.version)?(_seqsuffix)?'
    - a minimum length of 3 characters is suggested for typecodes, but 1 or 2 characters
      will be accepted
    - typecodes must correspond 1:1 to a class in the NMDC schema. this will be checked
      via per-class id slot usage assertions
    - minting authority shoulders should probably be enumerated and checked in the
      pattern
    examples:
    - value: nmdc:mgmag-00-x012.1_7_c1
      description: https://github.com/microbiomedata/nmdc-schema/pull/499#discussion_r1018499248
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    identifier: true
    alias: id
    owner: PlannedProcess
    domain_of:
    - Biosample
    - Study
    - Activity
    - NamedThing
    range: string
    required: true
  name:
    name: name
    description: A human readable label for an entity
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    alias: name
    owner: PlannedProcess
    domain_of:
    - Activity
    - NamedThing
    - PersonValue
    range: string
  description:
    name: description
    description: a human-readable description of a thing
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    slot_uri: dcterms:description
    alias: description
    owner: PlannedProcess
    domain_of:
    - NamedThing
    - ImageValue
    range: string
  alternative_identifiers:
    name: alternative_identifiers
    description: A list of alternative identifiers for the entity.
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 1000
    multivalued: true
    alias: alternative_identifiers
    owner: PlannedProcess
    domain_of:
    - Biosample
    - Study
    - NamedThing
    - MetaboliteQuantification
    range: string
class_uri: OBI:0000011
```

**Comment by turbomam** [comment]
---

```yaml
pooling_set:
  - id: bare:value
    name: first pooling process
    alternative_identifiers:
      - bare:xxx
    description: xxx
    has_inputs:
      - bare:xxx
      - bare:yyy
    has_outputs:
      - bare:xxx
    # participating_agent: xxx # Agent isn't a named thing and doesn't have an ID so must be inlined
```
